/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Abuse Management Admin API
 * Administrative API for managing abuse cases, reports, and related resources
 * OpenAPI spec version: 1.0.0
 */
/**
 * Type of abuse case
 */
export type CaseType = (typeof CaseType)[keyof typeof CaseType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CaseType = {
  spam: "spam",
  harassment: "harassment",
  content: "content",
  malware: "malware",
  other: "other",
} as const;

/**
 * Current status of the case
 */
export type CaseStatus = (typeof CaseStatus)[keyof typeof CaseStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CaseStatus = {
  new: "new",
  in_progress: "in_progress",
  resolved: "resolved",
  closed: "closed",
} as const;

/**
 * Priority level for the case
 */
export type CasePriority = (typeof CasePriority)[keyof typeof CasePriority];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CasePriority = {
  low: "low",
  medium: "medium",
  high: "high",
  critical: "critical",
} as const;

/**
 * Type of subject identifier
 */
export type SubjectType = (typeof SubjectType)[keyof typeof SubjectType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SubjectType = {
  hash: "hash",
  url: "url",
} as const;

/**
 * Source of the case
 */
export type ReportSource = (typeof ReportSource)[keyof typeof ReportSource];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ReportSource = {
  web_form: "web_form",
  email: "email",
  api: "api",
  system: "system",
} as const;

/**
 * Status of the scan
 */
export type ScanStatus = (typeof ScanStatus)[keyof typeof ScanStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ScanStatus = {
  scheduled: "scheduled",
  in_progress: "in_progress",
  completed: "completed",
  failed: "failed",
} as const;

/**
 * Type of communication
 */
export type CommunicationType =
  (typeof CommunicationType)[keyof typeof CommunicationType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CommunicationType = {
  email: "email",
  note: "note",
  response: "response",
} as const;

/**
 * Direction of communication
 */
export type CommunicationDirection =
  (typeof CommunicationDirection)[keyof typeof CommunicationDirection];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CommunicationDirection = {
  incoming: "incoming",
  outgoing: "outgoing",
  internal: "internal",
  external: "external",
} as const;

/**
 * Source of the evidence
 */
export type EvidenceSource =
  (typeof EvidenceSource)[keyof typeof EvidenceSource];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EvidenceSource = {
  email: "email",
  web_upload: "web_upload",
  api: "api",
  system: "system",
} as const;

/**
 * Reason for blocking content
 */
export type BlockReason = (typeof BlockReason)[keyof typeof BlockReason];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BlockReason = {
  malware: "malware",
  csam: "csam",
  copyright: "copyright",
  harassment: "harassment",
  hate_speech: "hate_speech",
  spam: "spam",
  system_policy: "system_policy",
  manual: "manual",
} as const;

/**
 * Severity of the blocked content
 */
export type BlockSeverity = (typeof BlockSeverity)[keyof typeof BlockSeverity];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BlockSeverity = {
  critical: "critical",
  high: "high",
  medium: "medium",
  low: "low",
} as const;

/**
 * Action taken for the blocked content
 */
export type BlockAction = (typeof BlockAction)[keyof typeof BlockAction];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BlockAction = {
  reject: "reject",
  quarantine: "quarantine",
  warn: "warn",
  log: "log",
} as const;

/**
 * Source of the block
 */
export type BlockSource = (typeof BlockSource)[keyof typeof BlockSource];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BlockSource = {
  scanner: "scanner",
  report: "report",
  admin: "admin",
  external: "external",
} as const;

export interface BaseResponse {
  /** Unique identifier */
  id: number;
  /** When the record was created */
  created_at: string;
  /** When the record was last updated */
  updated_at: string;
}

export interface CreateCaseRequest {
  /** Type of abuse case */
  type: CaseType;
  /**
   * Detailed description of the case
   * @minLength 10
   */
  description: string;
  /** Priority level for the case */
  priority?: CasePriority;
  /** Source of the case */
  source?: ReportSource;
  /** Whether the case needs manual review */
  needs_review?: boolean;
  /** ID of the reporter */
  reporter_id: number;
  /** ID of the subject */
  subject_id: number;
}

export interface CaseUpdateRequest {
  /** Updated description of the case */
  description?: string;
  /** Updated type of abuse case */
  type?: CaseType;
  /** Updated priority level */
  priority?: CasePriority;
  /** Updated source of the case */
  source?: ReportSource;
  /** Whether the case needs manual review */
  needs_review?: boolean;
  /** ID of the reporter */
  reporter_id?: number;
  /** ID of the subject */
  subject_id?: number;
}

export interface CaseStatusUpdateRequest {
  /** New status for the case */
  status: CaseStatus;
}

export type CaseStatusResponseAllOf = {
  /** Previous status of the case */
  old_status: CaseStatus;
  /** New status of the case */
  new_status: CaseStatus;
};

export type CaseStatusResponse = BaseResponse & CaseStatusResponseAllOf;

export type CaseResponseAllOf = {
  /** Human-readable reference number */
  reference_number: string;
  /** Type of abuse case */
  type: CaseType;
  /** Current status of the case */
  status: CaseStatus;
  /** Priority level for the case */
  priority: CasePriority;
  /** Detailed description of the case */
  description: string;
  /** Source of the case */
  source: ReportSource;
  /** Whether the case needs manual review */
  needs_review: boolean;
  /** ID of the reporter */
  reporter_id: number;
  /** ID of the subject */
  subject_id: number;
  /** List of associated communications */
  communications?: CommunicationResponse[];
  /** List of associated scans */
  scans?: ScanResponse[];
};

export type CaseResponse = BaseResponse & CaseResponseAllOf;

export interface CaseListResponse {
  data: CaseResponse[];
  pagination: PaginationInfo;
}

export interface ReporterCreateRequest {
  /** Email address of the reporter */
  email: string;
  /**
   * Name of the reporter
   * @minLength 2
   */
  name: string;
}

export type ReporterResponseAllOf = {
  /** Email address of the reporter */
  email: string;
  /** Name of the reporter */
  name: string;
};

export type ReporterResponse = BaseResponse & ReporterResponseAllOf;

export interface ReporterListResponse {
  data: ReporterResponse[];
  pagination: PaginationInfo;
}

export interface SubjectCreateRequest {
  /**
   * Identifier for the subject (content hash/CID)
   * @minLength 3
   */
  identifier: string;
  /** Type of subject identifier */
  type: SubjectType;
}

export type SubjectResponseAllOf = {
  /** Identifier for the subject (content hash/CID) */
  identifier: string;
};

export type SubjectResponse = BaseResponse & SubjectResponseAllOf;

export interface SubjectListResponse {
  data: SubjectResponse[];
  pagination: PaginationInfo;
}

export interface ManualScanRequest {
  /** ID of the case for which to initiate a scan */
  case_id: number;
}

export interface ScanInitiatedResponse {
  /** Whether the scan was successfully initiated */
  success: boolean;
  /** ID of the created scan */
  scanId: number;
  /** Informational message */
  message?: string;
}

export interface CommunicationCreateRequest {
  /** Content of the communication */
  content: string;
  /** Type of communication */
  type: CommunicationType;
  /** Direction of communication */
  direction: CommunicationDirection;
  /**
   * ID of parent communication for threading
   * @nullable
   */
  parent_id?: number | null;
}

export interface CommunicationUpdateRequest {
  /** Updated content of the communication */
  content?: string;
  /** Updated type of communication */
  type?: CommunicationType;
  /** Updated direction of communication */
  direction?: CommunicationDirection;
  /**
   * Updated ID of parent communication for threading
   * @nullable
   */
  parent_id?: number | null;
}

export type CommunicationResponseAllOf = {
  /** Content of the communication */
  content: string;
  /** Type of communication */
  type: CommunicationType;
  /** Direction of communication */
  direction: CommunicationDirection;
  /**
   * ID of parent communication for threading
   * @nullable
   */
  parent_id?: number | null;
};

export type CommunicationResponse = BaseResponse & CommunicationResponseAllOf;

export interface CommunicationListResponse {
  data: CommunicationResponse[];
  pagination: PaginationInfo;
}

export type ScanResponseAllOf = {
  /** ID of the associated case */
  case_id: number;
  /** ID of the associated subject */
  subject_id: number;
  /** Status of the scan */
  status: ScanStatus;
  /** When the scan is scheduled to run */
  scheduled_at: string;
  /**
   * When the scan was last attempted
   * @nullable
   */
  started_at?: string | null;
  /**
   * When the scan was last attempted
   * @nullable
   */
  completed_at?: string | null;
};

export type ScanResponse = BaseResponse & ScanResponseAllOf;

export interface ScanListResponse {
  data: ScanResponse[];
  pagination: PaginationInfo;
}

/**
 * Additional metadata about the scan
 */
export type ScanResultResponseMetadata = { [key: string]: unknown };

export interface ScanResultResponse {
  /** Whether the scan passed */
  passed: boolean;
  /** Reason for scan result */
  reason?: string;
  /** When the scan result was generated */
  timestamp: string;
  /** Identifier for the scanner */
  scanner_id: string;
  /** Additional metadata about the scan */
  metadata?: ScanResultResponseMetadata;
}

export interface ScanResultListResponse {
  data: ScanResultResponse[];
}

/**
 * Additional metadata about the evidence
 */
export type EvidenceCreateRequestMetadata = { [key: string]: unknown };

export interface EvidenceCreateRequest {
  /** Name of the uploaded file */
  file_name: string;
  /** MIME type of the file */
  content_type: string;
  /** Source of the evidence */
  source: EvidenceSource;
  /** Description of the evidence */
  description?: string;
  /** Additional metadata about the evidence */
  metadata?: EvidenceCreateRequestMetadata;
}

/**
 * Additional metadata about the evidence
 */
export type EvidenceResponseAllOfMetadata = { [key: string]: unknown };

export type EvidenceResponseAllOf = {
  /** ID of the associated case */
  case_id: number;
  /** ID of the user who submitted the evidence */
  submitter_id: number;
  /** Name of the evidence file */
  file_name: string;
  /** MIME type of the evidence */
  content_type: string;
  /** Storage hash (CID) of the evidence content */
  storage_hash?: string;
  /** Size of the evidence file in bytes */
  file_size: number;
  /** Source of the evidence */
  source: EvidenceSource;
  /** Description of the evidence */
  description?: string;
  /** Additional metadata about the evidence */
  metadata?: EvidenceResponseAllOfMetadata;
};

export type EvidenceResponse = BaseResponse & EvidenceResponseAllOf;

export interface EvidenceListResponse {
  data: EvidenceResponse[];
  pagination: PaginationInfo;
}

/**
 * Additional metadata about the block
 */
export type BlockContentCreateRequestMetadata = { [key: string]: unknown };

export interface BlockContentCreateRequest {
  /** Multihash of the content to block */
  hash: string;
  /** Content type if known */
  mime_type?: string;
  /** Original filename if known */
  file_name?: string;
  /** Size if known */
  size?: number;
  /**
   * ID of the user who uploaded the content
   * @nullable
   */
  uploader_id?: number | null;
  /** Reason for blocking content */
  reason: BlockReason;
  /** Severity of the blocked content */
  severity: BlockSeverity;
  /** Action taken for the blocked content */
  action: BlockAction;
  /** Description of the block */
  description?: string;
  /** Source of the block */
  source?: BlockSource;
  /**
   * ID of the associated case
   * @nullable
   */
  case_id?: number | null;
  /**
   * When the block expires
   * @nullable
   */
  expires_at?: string | null;
  /** Additional metadata about the block */
  metadata?: BlockContentCreateRequestMetadata;
}

/**
 * Additional metadata about the block
 */
export type BlockContentResponseMetadata = { [key: string]: unknown };

export interface BlockContentResponse {
  /** Unique identifier for the block entry */
  id: number;
  /** Multihash of the blocked content */
  hash: string;
  /** Content type if known */
  mime_type?: string;
  /** Original filename if known */
  file_name?: string;
  /** Size if known */
  size?: number;
  /**
   * ID of the user who uploaded the content
   * @nullable
   */
  uploader_id?: number | null;
  /** Reason for blocking content */
  reason: BlockReason;
  /** Severity of the blocked content */
  severity: BlockSeverity;
  /** Action taken for the blocked content */
  action: BlockAction;
  /** Description of the block */
  description?: string;
  /** ID of the user who created the block */
  blocked_by: number;
  /** Source of the block */
  source?: BlockSource;
  /**
   * ID of the associated case
   * @nullable
   */
  case_id?: number | null;
  /**
   * When the block expires
   * @nullable
   */
  expires_at?: string | null;
  /**
   * When the block was last reviewed
   * @nullable
   */
  reviewed_at?: string | null;
  /** When the block was created */
  created_at: string;
  /** When the block was last updated */
  updated_at: string;
  /** Additional metadata about the block */
  metadata?: BlockContentResponseMetadata;
}

export interface BlockListResponse {
  items: BlockContentResponse[];
  /** Total number of blocked content items */
  total_count: number;
}

export interface Distribution {
  /** Name of the category (e.g., status, type) */
  name: string;
  /** Count for the category */
  count: number;
}

export interface ResolutionTrend {
  /** Date for the trend data */
  date: string;
  /** Number of cases resolved on this date */
  resolved_count: number;
  /** Average resolution time in seconds for cases resolved on this date */
  average_seconds: number;
}

export interface ResolutionMetrics {
  /** Overall average resolution time in seconds */
  average_seconds: number;
  /** Daily trends for case resolution */
  daily_trends: ResolutionTrend[];
}

export interface CommunicationsMetrics {
  /** Average time in seconds to first response */
  average_response_seconds: number;
  /** Maximum time in seconds to first response */
  max_response_seconds: number;
  /** Distribution of communication counts per case */
  counts_per_case: Distribution[];
}

export interface EvidenceMetrics {
  /** Distribution of evidence file counts per case */
  files_per_case: Distribution[];
  /** Average number of evidence files per case */
  average_per_case: number;
}

export interface BlocklistMetrics {
  /** Total number of blocked items */
  total_blocks: number;
  /** Distribution of blocks by reason */
  by_reason: Distribution[];
  /** Distribution of blocks by severity */
  by_severity: Distribution[];
}

export interface DurationDistribution {
  /** Case status */
  status: CaseStatus;
  /** Duration in seconds for this status */
  duration_seconds: number;
}

export type CaseAnalyticsResponseAllOf = {
  /** Total number of cases */
  total_cases: number;
  /** Number of open cases */
  open_cases: number;
  /** Number of new cases in the specified range */
  new_cases: number;
  /** Number of cases needing review */
  needs_review_count: number;
  /** Distribution of cases by status */
  status_distribution: Distribution[];
  /** Distribution of cases by type */
  case_type_distribution: Distribution[];
  /** Distribution of cases by source */
  source_distribution: Distribution[];
  /** Metrics related to case resolution time */
  resolution_metrics: ResolutionMetrics;
  /** Durations spent in each status for resolved cases */
  status_durations: DurationDistribution[];
  /** Average durations spent in each status */
  avg_status_durations: DurationDistribution[];
  /** Metrics related to case communications */
  communications: CommunicationsMetrics;
  /** Metrics related to case evidence */
  evidence: EvidenceMetrics;
  /** Metrics related to the blocklist */
  blocklist: BlocklistMetrics;
};

export type CaseAnalyticsResponse = BaseResponse & CaseAnalyticsResponseAllOf;

export interface GlobalSearchResponse {
  /** List of matching cases */
  cases: CaseResponse[];
  /** List of matching reporters */
  reporters: ReporterResponse[];
  /** Total number of matching items across all types */
  total_count: number;
}

export interface PaginationInfo {
  /** Current page number */
  currentPage: number;
  /** Total number of pages */
  totalPages: number;
  /** Total number of items */
  totalItems: number;
  /** Number of items per page */
  itemsPerPage: number;
}

/**
 * Additional error details
 */
export type ErrorResponseDetails = { [key: string]: unknown };

export interface ErrorResponse {
  /** Error message */
  error: string;
  /** Additional error details */
  details?: ErrorResponseDetails;
}

/**
 * Page number for pagination
 */
export type PageParamParameter = number;

/**
 * Number of items per page
 */
export type LimitParamParameter = number;

/**
 * Sort field and direction (e.g. created_at:desc)
 */
export type SortParamParameter = string;

/**
 * Generic filter parameter (field:value)
 */
export type FilterParamParameter = string;

export type ListCasesParams = {
  /**
   * Page number for pagination
   */
  page?: PageParamParameter;
  /**
   * Number of items per page
   */
  limit?: LimitParamParameter;
  /**
   * Sort field and direction (e.g. created_at:desc)
   */
  sort?: SortParamParameter;
  /**
   * Generic filter parameter (field:value)
   */
  filter?: FilterParamParameter;
  /**
   * Filter by case status
   */
  status?: CaseStatus;
  /**
   * Filter by case type
   */
  type?: CaseType;
  /**
   * Filter by case priority
   */
  priority?: CasePriority;
};

export type ListCaseCommunicationsParams = {
  /**
   * Page number for pagination
   */
  page?: PageParamParameter;
  /**
   * Number of items per page
   */
  limit?: LimitParamParameter;
  /**
   * Sort field and direction (e.g. created_at:desc)
   */
  sort?: SortParamParameter;
};

export type ListCaseScansParams = {
  /**
   * Page number for pagination
   */
  page?: PageParamParameter;
  /**
   * Number of items per page
   */
  limit?: LimitParamParameter;
  /**
   * Sort field and direction (e.g. created_at:desc)
   */
  sort?: SortParamParameter;
};

export type CreateScanRequest202 = {
  /** Status message */
  message?: string;
};

export type ListCaseEvidenceParams = {
  /**
   * Page number for pagination
   */
  page?: PageParamParameter;
  /**
   * Number of items per page
   */
  limit?: LimitParamParameter;
  /**
   * Sort field and direction (e.g. created_at:desc)
   */
  sort?: SortParamParameter;
};

export type UploadEvidenceBody = {
  /** The evidence file to upload */
  file: Blob;
  /** JSON string containing EvidenceCreateRequest data (file_name, content_type, source, description, metadata) */
  data: string;
};

export type GetScanResults200 = {
  data: ScanResultResponse[];
};

export type ListReportersParams = {
  /**
   * Page number for pagination
   */
  page?: PageParamParameter;
  /**
   * Number of items per page
   */
  limit?: LimitParamParameter;
  /**
   * Sort field and direction (e.g. created_at:desc)
   */
  sort?: SortParamParameter;
  /**
   * Generic filter parameter (field:value)
   */
  filter?: FilterParamParameter;
  /**
   * Filter by email address
   */
  email?: string;
};

export type ListSubjectsParams = {
  /**
   * Page number for pagination
   */
  page?: PageParamParameter;
  /**
   * Number of items per page
   */
  limit?: LimitParamParameter;
  /**
   * Sort field and direction (e.g. created_at:desc)
   */
  sort?: SortParamParameter;
  /**
   * Generic filter parameter (field:value)
   */
  filter?: FilterParamParameter;
  /**
   * Filter by subject identifier
   */
  identifier?: string;
};

export type ListBlockedContentParams = {
  /**
   * Page number for pagination
   */
  page?: PageParamParameter;
  /**
   * Number of items per page
   */
  limit?: LimitParamParameter;
  /**
   * Sort field and direction (e.g. created_at:desc)
   */
  sort?: SortParamParameter;
  /**
   * Generic filter parameter (field:value)
   */
  filter?: FilterParamParameter;
  /**
   * Filter by content hash
   */
  hash?: string;
  /**
   * Filter by block reason
   */
  reason?: BlockReason;
  /**
   * Filter by block severity
   */
  severity?: BlockSeverity;
  /**
   * Filter by block action
   */
  action?: BlockAction;
  /**
   * Filter by block source
   */
  source?: BlockSource;
  /**
   * Filter by associated case ID
   */
  case_id?: number;
};

export type GetCaseAnalyticsParams = {
  /**
   * Generic filter parameter (field:value)
   */
  filter?: FilterParamParameter;
};

export type SearchCasesParams = {
  /**
   * Search query string
   */
  q: string;
  /**
   * Page number for pagination
   */
  page?: PageParamParameter;
  /**
   * Number of items per page
   */
  limit?: LimitParamParameter;
  /**
   * Sort field and direction (e.g. created_at:desc)
   */
  sort?: SortParamParameter;
};

export type GlobalSearchParams = {
  /**
   * Search query string
   */
  q: string;
  /**
   * Page number for pagination
   */
  page?: PageParamParameter;
  /**
   * Number of items per page
   */
  limit?: LimitParamParameter;
};
