/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Portal Admin API
 * Provides administrative endpoints for managing the Portal.
 * OpenAPI spec version: unknown
 */
import type {
  BlockReasonListResponse,
  CaseAnalyticsResponse,
  CaseTypeSourceMatrixResponse,
  CommunicationTimelineResponse,
  ErrorResponse,
  GetApiAbuseAnalyticsBlocklistBlockReasonsParams,
  GetApiAbuseAnalyticsCasesParams,
  GetApiAbuseAnalyticsCasesStatusFlowParams,
  GetApiAbuseAnalyticsCasesTimeSeriesParams,
  GetApiAbuseAnalyticsCasesTypeSourceMatrixParams,
  GetApiAbuseAnalyticsCommunicationsTimelineParams,
  StatusFlowGraph
} from './portalAdminAPI.schemas';



/**
 * Retrieve a breakdown of block counts by block reason over a specified time range.
 * @summary Get block reason counts
 */
export type getApiAbuseAnalyticsBlocklistBlockReasonsResponse200 = {
  data: BlockReasonListResponse
  status: 200
}

export type getApiAbuseAnalyticsBlocklistBlockReasonsResponse400 = {
  data: ErrorResponse
  status: 400
}
    
export type getApiAbuseAnalyticsBlocklistBlockReasonsResponseComposite = getApiAbuseAnalyticsBlocklistBlockReasonsResponse200 | getApiAbuseAnalyticsBlocklistBlockReasonsResponse400;
    
export type getApiAbuseAnalyticsBlocklistBlockReasonsResponse = getApiAbuseAnalyticsBlocklistBlockReasonsResponseComposite & {
  headers: Headers;
}

export const getGetApiAbuseAnalyticsBlocklistBlockReasonsUrl = (params?: GetApiAbuseAnalyticsBlocklistBlockReasonsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/api/abuse/analytics/blocklist/block-reasons?${stringifiedParams}` : `/api/api/abuse/analytics/blocklist/block-reasons`
}

export const getApiAbuseAnalyticsBlocklistBlockReasons = async (params?: GetApiAbuseAnalyticsBlocklistBlockReasonsParams, options?: RequestInit): Promise<getApiAbuseAnalyticsBlocklistBlockReasonsResponse> => {
  
  const res = await fetch(getGetApiAbuseAnalyticsBlocklistBlockReasonsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: getApiAbuseAnalyticsBlocklistBlockReasonsResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as getApiAbuseAnalyticsBlocklistBlockReasonsResponse
}


/**
 * Retrieve overall case analytics with optional filtering
 * @summary Get case analytics
 */
export type getApiAbuseAnalyticsCasesResponse200 = {
  data: CaseAnalyticsResponse
  status: 200
}

export type getApiAbuseAnalyticsCasesResponse400 = {
  data: ErrorResponse
  status: 400
}
    
export type getApiAbuseAnalyticsCasesResponseComposite = getApiAbuseAnalyticsCasesResponse200 | getApiAbuseAnalyticsCasesResponse400;
    
export type getApiAbuseAnalyticsCasesResponse = getApiAbuseAnalyticsCasesResponseComposite & {
  headers: Headers;
}

export const getGetApiAbuseAnalyticsCasesUrl = (params?: GetApiAbuseAnalyticsCasesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/api/abuse/analytics/cases?${stringifiedParams}` : `/api/api/abuse/analytics/cases`
}

export const getApiAbuseAnalyticsCases = async (params?: GetApiAbuseAnalyticsCasesParams, options?: RequestInit): Promise<getApiAbuseAnalyticsCasesResponse> => {
  
  const res = await fetch(getGetApiAbuseAnalyticsCasesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: getApiAbuseAnalyticsCasesResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as getApiAbuseAnalyticsCasesResponse
}


/**
 * Retrieve case analytics for the last 24 hours
 * @summary Get 24-hour case analytics
 */
export type getApiAbuseAnalyticsCases24hResponse200 = {
  data: CaseAnalyticsResponse
  status: 200
}

export type getApiAbuseAnalyticsCases24hResponse400 = {
  data: ErrorResponse
  status: 400
}
    
export type getApiAbuseAnalyticsCases24hResponseComposite = getApiAbuseAnalyticsCases24hResponse200 | getApiAbuseAnalyticsCases24hResponse400;
    
export type getApiAbuseAnalyticsCases24hResponse = getApiAbuseAnalyticsCases24hResponseComposite & {
  headers: Headers;
}

export const getGetApiAbuseAnalyticsCases24hUrl = () => {


  

  return `/api/api/abuse/analytics/cases/24h`
}

export const getApiAbuseAnalyticsCases24h = async ( options?: RequestInit): Promise<getApiAbuseAnalyticsCases24hResponse> => {
  
  const res = await fetch(getGetApiAbuseAnalyticsCases24hUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: getApiAbuseAnalyticsCases24hResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as getApiAbuseAnalyticsCases24hResponse
}


/**
 * Retrieve case analytics for the last 30 days
 * @summary Get 30-day case analytics
 */
export type getApiAbuseAnalyticsCases30dResponse200 = {
  data: CaseAnalyticsResponse
  status: 200
}

export type getApiAbuseAnalyticsCases30dResponse400 = {
  data: ErrorResponse
  status: 400
}
    
export type getApiAbuseAnalyticsCases30dResponseComposite = getApiAbuseAnalyticsCases30dResponse200 | getApiAbuseAnalyticsCases30dResponse400;
    
export type getApiAbuseAnalyticsCases30dResponse = getApiAbuseAnalyticsCases30dResponseComposite & {
  headers: Headers;
}

export const getGetApiAbuseAnalyticsCases30dUrl = () => {


  

  return `/api/api/abuse/analytics/cases/30d`
}

export const getApiAbuseAnalyticsCases30d = async ( options?: RequestInit): Promise<getApiAbuseAnalyticsCases30dResponse> => {
  
  const res = await fetch(getGetApiAbuseAnalyticsCases30dUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: getApiAbuseAnalyticsCases30dResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as getApiAbuseAnalyticsCases30dResponse
}


/**
 * Retrieve case analytics for the last 7 days
 * @summary Get 7-day case analytics
 */
export type getApiAbuseAnalyticsCases7dResponse200 = {
  data: CaseAnalyticsResponse
  status: 200
}

export type getApiAbuseAnalyticsCases7dResponse400 = {
  data: ErrorResponse
  status: 400
}
    
export type getApiAbuseAnalyticsCases7dResponseComposite = getApiAbuseAnalyticsCases7dResponse200 | getApiAbuseAnalyticsCases7dResponse400;
    
export type getApiAbuseAnalyticsCases7dResponse = getApiAbuseAnalyticsCases7dResponseComposite & {
  headers: Headers;
}

export const getGetApiAbuseAnalyticsCases7dUrl = () => {


  

  return `/api/api/abuse/analytics/cases/7d`
}

export const getApiAbuseAnalyticsCases7d = async ( options?: RequestInit): Promise<getApiAbuseAnalyticsCases7dResponse> => {
  
  const res = await fetch(getGetApiAbuseAnalyticsCases7dUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: getApiAbuseAnalyticsCases7dResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as getApiAbuseAnalyticsCases7dResponse
}


/**
 * Retrieve status transition data for visualization
 * @summary Get case status flow
 */
export type getApiAbuseAnalyticsCasesStatusFlowResponse200 = {
  data: StatusFlowGraph
  status: 200
}

export type getApiAbuseAnalyticsCasesStatusFlowResponse400 = {
  data: ErrorResponse
  status: 400
}
    
export type getApiAbuseAnalyticsCasesStatusFlowResponseComposite = getApiAbuseAnalyticsCasesStatusFlowResponse200 | getApiAbuseAnalyticsCasesStatusFlowResponse400;
    
export type getApiAbuseAnalyticsCasesStatusFlowResponse = getApiAbuseAnalyticsCasesStatusFlowResponseComposite & {
  headers: Headers;
}

export const getGetApiAbuseAnalyticsCasesStatusFlowUrl = (params?: GetApiAbuseAnalyticsCasesStatusFlowParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/api/abuse/analytics/cases/status-flow?${stringifiedParams}` : `/api/api/abuse/analytics/cases/status-flow`
}

export const getApiAbuseAnalyticsCasesStatusFlow = async (params?: GetApiAbuseAnalyticsCasesStatusFlowParams, options?: RequestInit): Promise<getApiAbuseAnalyticsCasesStatusFlowResponse> => {
  
  const res = await fetch(getGetApiAbuseAnalyticsCasesStatusFlowUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: getApiAbuseAnalyticsCasesStatusFlowResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as getApiAbuseAnalyticsCasesStatusFlowResponse
}


/**
 * Retrieve time-series metrics for cases (open, new, resolved) with optional filtering
 * @summary Get case time-series metrics
 */
export type getApiAbuseAnalyticsCasesTimeSeriesResponse200 = {
  data: number[]
  status: 200
}

export type getApiAbuseAnalyticsCasesTimeSeriesResponse400 = {
  data: ErrorResponse
  status: 400
}
    
export type getApiAbuseAnalyticsCasesTimeSeriesResponseComposite = getApiAbuseAnalyticsCasesTimeSeriesResponse200 | getApiAbuseAnalyticsCasesTimeSeriesResponse400;
    
export type getApiAbuseAnalyticsCasesTimeSeriesResponse = getApiAbuseAnalyticsCasesTimeSeriesResponseComposite & {
  headers: Headers;
}

export const getGetApiAbuseAnalyticsCasesTimeSeriesUrl = (params?: GetApiAbuseAnalyticsCasesTimeSeriesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/api/abuse/analytics/cases/time-series?${stringifiedParams}` : `/api/api/abuse/analytics/cases/time-series`
}

export const getApiAbuseAnalyticsCasesTimeSeries = async (params?: GetApiAbuseAnalyticsCasesTimeSeriesParams, options?: RequestInit): Promise<getApiAbuseAnalyticsCasesTimeSeriesResponse> => {
  
  const res = await fetch(getGetApiAbuseAnalyticsCasesTimeSeriesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: getApiAbuseAnalyticsCasesTimeSeriesResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as getApiAbuseAnalyticsCasesTimeSeriesResponse
}


/**
 * Retrieve a breakdown of case counts by case type and report source over a specified time range.
 * @summary Get case type and source matrix
 */
export type getApiAbuseAnalyticsCasesTypeSourceMatrixResponse200 = {
  data: CaseTypeSourceMatrixResponse
  status: 200
}

export type getApiAbuseAnalyticsCasesTypeSourceMatrixResponse400 = {
  data: ErrorResponse
  status: 400
}
    
export type getApiAbuseAnalyticsCasesTypeSourceMatrixResponseComposite = getApiAbuseAnalyticsCasesTypeSourceMatrixResponse200 | getApiAbuseAnalyticsCasesTypeSourceMatrixResponse400;
    
export type getApiAbuseAnalyticsCasesTypeSourceMatrixResponse = getApiAbuseAnalyticsCasesTypeSourceMatrixResponseComposite & {
  headers: Headers;
}

export const getGetApiAbuseAnalyticsCasesTypeSourceMatrixUrl = (params?: GetApiAbuseAnalyticsCasesTypeSourceMatrixParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/api/abuse/analytics/cases/type-source-matrix?${stringifiedParams}` : `/api/api/abuse/analytics/cases/type-source-matrix`
}

export const getApiAbuseAnalyticsCasesTypeSourceMatrix = async (params?: GetApiAbuseAnalyticsCasesTypeSourceMatrixParams, options?: RequestInit): Promise<getApiAbuseAnalyticsCasesTypeSourceMatrixResponse> => {
  
  const res = await fetch(getGetApiAbuseAnalyticsCasesTypeSourceMatrixUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: getApiAbuseAnalyticsCasesTypeSourceMatrixResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as getApiAbuseAnalyticsCasesTypeSourceMatrixResponse
}


/**
 * Retrieve a timeline of communication counts per hour over a specified time range.
 * @summary Get communication timeline
 */
export type getApiAbuseAnalyticsCommunicationsTimelineResponse200 = {
  data: CommunicationTimelineResponse
  status: 200
}

export type getApiAbuseAnalyticsCommunicationsTimelineResponse400 = {
  data: ErrorResponse
  status: 400
}
    
export type getApiAbuseAnalyticsCommunicationsTimelineResponseComposite = getApiAbuseAnalyticsCommunicationsTimelineResponse200 | getApiAbuseAnalyticsCommunicationsTimelineResponse400;
    
export type getApiAbuseAnalyticsCommunicationsTimelineResponse = getApiAbuseAnalyticsCommunicationsTimelineResponseComposite & {
  headers: Headers;
}

export const getGetApiAbuseAnalyticsCommunicationsTimelineUrl = (params?: GetApiAbuseAnalyticsCommunicationsTimelineParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/api/abuse/analytics/communications/timeline?${stringifiedParams}` : `/api/api/abuse/analytics/communications/timeline`
}

export const getApiAbuseAnalyticsCommunicationsTimeline = async (params?: GetApiAbuseAnalyticsCommunicationsTimelineParams, options?: RequestInit): Promise<getApiAbuseAnalyticsCommunicationsTimelineResponse> => {
  
  const res = await fetch(getGetApiAbuseAnalyticsCommunicationsTimelineUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: getApiAbuseAnalyticsCommunicationsTimelineResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as getApiAbuseAnalyticsCommunicationsTimelineResponse
}


