/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Portal Admin API
 * Provides administrative endpoints for managing the Portal.
 * OpenAPI spec version: unknown
 */
import type {
  ErrorResponse,
  GetApiAbuseBlocklistParams,
  GetApiAbuseCases200,
  GetApiAbuseCasesCaseIdScansParams,
  GetApiAbuseCasesCaseIdScansScanIdResultsParams,
  GetApiAbuseCasesIdCommunicationsParams,
  GetApiAbuseCasesIdEvidenceParams,
  GetApiAbuseCasesParams,
  GetApiAbuseReportersParams,
  GetApiAbuseSearchCasesParams,
  GetApiAbuseSubjectsParams
} from './portalAdminAPI.schemas';



/**
 * Retrieve a list of blocked content items with optional filtering and pagination
 * @summary List Blocked Content
 */
export type getApiAbuseBlocklistResponse200 = {
  data: void
  status: 200
}

export type getApiAbuseBlocklistResponse400 = {
  data: ErrorResponse
  status: 400
}
    
export type getApiAbuseBlocklistResponseComposite = getApiAbuseBlocklistResponse200 | getApiAbuseBlocklistResponse400;
    
export type getApiAbuseBlocklistResponse = getApiAbuseBlocklistResponseComposite & {
  headers: Headers;
}

export const getGetApiAbuseBlocklistUrl = (params?: GetApiAbuseBlocklistParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/api/abuse/blocklist?${stringifiedParams}` : `/api/api/abuse/blocklist`
}

export const getApiAbuseBlocklist = async (params?: GetApiAbuseBlocklistParams, options?: RequestInit): Promise<getApiAbuseBlocklistResponse> => {
  
  const res = await fetch(getGetApiAbuseBlocklistUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: getApiAbuseBlocklistResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as getApiAbuseBlocklistResponse
}


/**
 * Retrieves a list of abuse cases with filtering and pagination
 * @summary List Cases
 */
export type getApiAbuseCasesResponse200 = {
  data: GetApiAbuseCases200
  status: 200
}

export type getApiAbuseCasesResponse400 = {
  data: ErrorResponse
  status: 400
}
    
export type getApiAbuseCasesResponseComposite = getApiAbuseCasesResponse200 | getApiAbuseCasesResponse400;
    
export type getApiAbuseCasesResponse = getApiAbuseCasesResponseComposite & {
  headers: Headers;
}

export const getGetApiAbuseCasesUrl = (params?: GetApiAbuseCasesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/api/abuse/cases?${stringifiedParams}` : `/api/api/abuse/cases`
}

export const getApiAbuseCases = async (params?: GetApiAbuseCasesParams, options?: RequestInit): Promise<getApiAbuseCasesResponse> => {
  
  const res = await fetch(getGetApiAbuseCasesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: getApiAbuseCasesResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as getApiAbuseCasesResponse
}


/**
 * Retrieve a list of scans for a specific case
 * @summary List case scans
 */
export type getApiAbuseCasesCaseIdScansResponse200 = {
  data: void
  status: 200
}

export type getApiAbuseCasesCaseIdScansResponse400 = {
  data: ErrorResponse
  status: 400
}
    
export type getApiAbuseCasesCaseIdScansResponseComposite = getApiAbuseCasesCaseIdScansResponse200 | getApiAbuseCasesCaseIdScansResponse400;
    
export type getApiAbuseCasesCaseIdScansResponse = getApiAbuseCasesCaseIdScansResponseComposite & {
  headers: Headers;
}

export const getGetApiAbuseCasesCaseIdScansUrl = (caseId: number,
    params?: GetApiAbuseCasesCaseIdScansParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/api/abuse/cases/${caseId}/scans?${stringifiedParams}` : `/api/api/abuse/cases/${caseId}/scans`
}

export const getApiAbuseCasesCaseIdScans = async (caseId: number,
    params?: GetApiAbuseCasesCaseIdScansParams, options?: RequestInit): Promise<getApiAbuseCasesCaseIdScansResponse> => {
  
  const res = await fetch(getGetApiAbuseCasesCaseIdScansUrl(caseId,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: getApiAbuseCasesCaseIdScansResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as getApiAbuseCasesCaseIdScansResponse
}


/**
 * Retrieve results of a specific scan with filtering, sorting, and pagination
 * @summary Get scan results
 */
export type getApiAbuseCasesCaseIdScansScanIdResultsResponse200 = {
  data: void
  status: 200
}

export type getApiAbuseCasesCaseIdScansScanIdResultsResponse400 = {
  data: ErrorResponse
  status: 400
}
    
export type getApiAbuseCasesCaseIdScansScanIdResultsResponseComposite = getApiAbuseCasesCaseIdScansScanIdResultsResponse200 | getApiAbuseCasesCaseIdScansScanIdResultsResponse400;
    
export type getApiAbuseCasesCaseIdScansScanIdResultsResponse = getApiAbuseCasesCaseIdScansScanIdResultsResponseComposite & {
  headers: Headers;
}

export const getGetApiAbuseCasesCaseIdScansScanIdResultsUrl = (caseId: number,
    scanId: number,
    params?: GetApiAbuseCasesCaseIdScansScanIdResultsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/api/abuse/cases/${caseId}/scans/${scanId}/results?${stringifiedParams}` : `/api/api/abuse/cases/${caseId}/scans/${scanId}/results`
}

export const getApiAbuseCasesCaseIdScansScanIdResults = async (caseId: number,
    scanId: number,
    params?: GetApiAbuseCasesCaseIdScansScanIdResultsParams, options?: RequestInit): Promise<getApiAbuseCasesCaseIdScansScanIdResultsResponse> => {
  
  const res = await fetch(getGetApiAbuseCasesCaseIdScansScanIdResultsUrl(caseId,scanId,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: getApiAbuseCasesCaseIdScansScanIdResultsResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as getApiAbuseCasesCaseIdScansScanIdResultsResponse
}


/**
 * Retrieve a list of communications for a specific case
 * @summary List case communications
 */
export type getApiAbuseCasesIdCommunicationsResponse200 = {
  data: void
  status: 200
}

export type getApiAbuseCasesIdCommunicationsResponse400 = {
  data: ErrorResponse
  status: 400
}
    
export type getApiAbuseCasesIdCommunicationsResponseComposite = getApiAbuseCasesIdCommunicationsResponse200 | getApiAbuseCasesIdCommunicationsResponse400;
    
export type getApiAbuseCasesIdCommunicationsResponse = getApiAbuseCasesIdCommunicationsResponseComposite & {
  headers: Headers;
}

export const getGetApiAbuseCasesIdCommunicationsUrl = (id: number,
    params?: GetApiAbuseCasesIdCommunicationsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/api/abuse/cases/${id}/communications?${stringifiedParams}` : `/api/api/abuse/cases/${id}/communications`
}

export const getApiAbuseCasesIdCommunications = async (id: number,
    params?: GetApiAbuseCasesIdCommunicationsParams, options?: RequestInit): Promise<getApiAbuseCasesIdCommunicationsResponse> => {
  
  const res = await fetch(getGetApiAbuseCasesIdCommunicationsUrl(id,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: getApiAbuseCasesIdCommunicationsResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as getApiAbuseCasesIdCommunicationsResponse
}


/**
 * Retrieve a list of evidence items for a specific case
 * @summary List case evidence
 */
export type getApiAbuseCasesIdEvidenceResponse200 = {
  data: void
  status: 200
}

export type getApiAbuseCasesIdEvidenceResponse400 = {
  data: ErrorResponse
  status: 400
}
    
export type getApiAbuseCasesIdEvidenceResponseComposite = getApiAbuseCasesIdEvidenceResponse200 | getApiAbuseCasesIdEvidenceResponse400;
    
export type getApiAbuseCasesIdEvidenceResponse = getApiAbuseCasesIdEvidenceResponseComposite & {
  headers: Headers;
}

export const getGetApiAbuseCasesIdEvidenceUrl = (id: number,
    params?: GetApiAbuseCasesIdEvidenceParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/api/abuse/cases/${id}/evidence?${stringifiedParams}` : `/api/api/abuse/cases/${id}/evidence`
}

export const getApiAbuseCasesIdEvidence = async (id: number,
    params?: GetApiAbuseCasesIdEvidenceParams, options?: RequestInit): Promise<getApiAbuseCasesIdEvidenceResponse> => {
  
  const res = await fetch(getGetApiAbuseCasesIdEvidenceUrl(id,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: getApiAbuseCasesIdEvidenceResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as getApiAbuseCasesIdEvidenceResponse
}


/**
 * Retrieve a list of reporters with optional filtering and pagination
 * @summary List reporters
 */
export type getApiAbuseReportersResponse200 = {
  data: void
  status: 200
}

export type getApiAbuseReportersResponse400 = {
  data: ErrorResponse
  status: 400
}
    
export type getApiAbuseReportersResponseComposite = getApiAbuseReportersResponse200 | getApiAbuseReportersResponse400;
    
export type getApiAbuseReportersResponse = getApiAbuseReportersResponseComposite & {
  headers: Headers;
}

export const getGetApiAbuseReportersUrl = (params?: GetApiAbuseReportersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/api/abuse/reporters?${stringifiedParams}` : `/api/api/abuse/reporters`
}

export const getApiAbuseReporters = async (params?: GetApiAbuseReportersParams, options?: RequestInit): Promise<getApiAbuseReportersResponse> => {
  
  const res = await fetch(getGetApiAbuseReportersUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: getApiAbuseReportersResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as getApiAbuseReportersResponse
}


/**
 * Search for abuse cases by query string with pagination and sorting
 * @summary Search cases
 */
export type getApiAbuseSearchCasesResponse200 = {
  data: void
  status: 200
}

export type getApiAbuseSearchCasesResponse400 = {
  data: ErrorResponse
  status: 400
}
    
export type getApiAbuseSearchCasesResponseComposite = getApiAbuseSearchCasesResponse200 | getApiAbuseSearchCasesResponse400;
    
export type getApiAbuseSearchCasesResponse = getApiAbuseSearchCasesResponseComposite & {
  headers: Headers;
}

export const getGetApiAbuseSearchCasesUrl = (params?: GetApiAbuseSearchCasesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/api/abuse/search/cases?${stringifiedParams}` : `/api/api/abuse/search/cases`
}

export const getApiAbuseSearchCases = async (params?: GetApiAbuseSearchCasesParams, options?: RequestInit): Promise<getApiAbuseSearchCasesResponse> => {
  
  const res = await fetch(getGetApiAbuseSearchCasesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: getApiAbuseSearchCasesResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as getApiAbuseSearchCasesResponse
}


/**
 * Retrieve a list of subjects with optional filtering and pagination
 * @summary List subjects
 */
export type getApiAbuseSubjectsResponse200 = {
  data: void
  status: 200
}

export type getApiAbuseSubjectsResponse400 = {
  data: ErrorResponse
  status: 400
}
    
export type getApiAbuseSubjectsResponseComposite = getApiAbuseSubjectsResponse200 | getApiAbuseSubjectsResponse400;
    
export type getApiAbuseSubjectsResponse = getApiAbuseSubjectsResponseComposite & {
  headers: Headers;
}

export const getGetApiAbuseSubjectsUrl = (params?: GetApiAbuseSubjectsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/api/abuse/subjects?${stringifiedParams}` : `/api/api/abuse/subjects`
}

export const getApiAbuseSubjects = async (params?: GetApiAbuseSubjectsParams, options?: RequestInit): Promise<getApiAbuseSubjectsResponse> => {
  
  const res = await fetch(getGetApiAbuseSubjectsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: getApiAbuseSubjectsResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as getApiAbuseSubjectsResponse
}


