/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Portal Admin API
 * Provides administrative endpoints for managing the Portal.
 * OpenAPI spec version: unknown
 */
import type {
  BlockContentCreateRequest,
  BlockContentResponse,
  ErrorResponse
} from './portalAdminAPI.schemas';



/**
 * Add a new content item to the block list
 * @summary Create block
 */
export type postApiAbuseBlocklistResponse200 = {
  data: ErrorResponse
  status: 200
}

export type postApiAbuseBlocklistResponse201 = {
  data: BlockContentResponse
  status: 201
}

export type postApiAbuseBlocklistResponse400 = {
  data: ErrorResponse
  status: 400
}
    
export type postApiAbuseBlocklistResponseComposite = postApiAbuseBlocklistResponse200 | postApiAbuseBlocklistResponse201 | postApiAbuseBlocklistResponse400;
    
export type postApiAbuseBlocklistResponse = postApiAbuseBlocklistResponseComposite & {
  headers: Headers;
}

export const getPostApiAbuseBlocklistUrl = () => {


  

  return `/api/api/abuse/blocklist`
}

export const postApiAbuseBlocklist = async (blockContentCreateRequest: BlockContentCreateRequest, options?: RequestInit): Promise<postApiAbuseBlocklistResponse> => {
  
  const res = await fetch(getPostApiAbuseBlocklistUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      blockContentCreateRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: postApiAbuseBlocklistResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as postApiAbuseBlocklistResponse
}


/**
 * Removes content from the block list by its hash.
 * @summary Unblock content
 */
export type deleteApiAbuseBlocklistHashResponse200 = {
  data: void
  status: 200
}

export type deleteApiAbuseBlocklistHashResponse400 = {
  data: ErrorResponse
  status: 400
}
    
export type deleteApiAbuseBlocklistHashResponseComposite = deleteApiAbuseBlocklistHashResponse200 | deleteApiAbuseBlocklistHashResponse400;
    
export type deleteApiAbuseBlocklistHashResponse = deleteApiAbuseBlocklistHashResponseComposite & {
  headers: Headers;
}

export const getDeleteApiAbuseBlocklistHashUrl = (hash: string,) => {


  

  return `/api/api/abuse/blocklist/${hash}`
}

export const deleteApiAbuseBlocklistHash = async (hash: string, options?: RequestInit): Promise<deleteApiAbuseBlocklistHashResponse> => {
  
  const res = await fetch(getDeleteApiAbuseBlocklistHashUrl(hash),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: deleteApiAbuseBlocklistHashResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as deleteApiAbuseBlocklistHashResponse
}


/**
 * Retrieve details of a specific blocked content item by its hash
 * @summary Get blocked content
 */
export type getApiAbuseBlocklistHashResponse200 = {
  data: BlockContentResponse
  status: 200
}

export type getApiAbuseBlocklistHashResponse400 = {
  data: ErrorResponse
  status: 400
}
    
export type getApiAbuseBlocklistHashResponseComposite = getApiAbuseBlocklistHashResponse200 | getApiAbuseBlocklistHashResponse400;
    
export type getApiAbuseBlocklistHashResponse = getApiAbuseBlocklistHashResponseComposite & {
  headers: Headers;
}

export const getGetApiAbuseBlocklistHashUrl = (hash: string,) => {


  

  return `/api/api/abuse/blocklist/${hash}`
}

export const getApiAbuseBlocklistHash = async (hash: string, options?: RequestInit): Promise<getApiAbuseBlocklistHashResponse> => {
  
  const res = await fetch(getGetApiAbuseBlocklistHashUrl(hash),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: getApiAbuseBlocklistHashResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as getApiAbuseBlocklistHashResponse
}


