/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Portal Admin API
 * Provides administrative endpoints for managing the Portal.
 * OpenAPI spec version: unknown
 */
import type {
  CaseResponse,
  CaseStatusResponse,
  CaseStatusUpdateRequest,
  CreateCaseRequest,
  ErrorResponse,
  UpdateCaseRequest
} from './portalAdminAPI.schemas';



/**
 * Creates a new abuse case
 * @summary Create Case
 */
export type postApiAbuseCasesResponse200 = {
  data: ErrorResponse
  status: 200
}

export type postApiAbuseCasesResponse201 = {
  data: CaseResponse
  status: 201
}

export type postApiAbuseCasesResponse400 = {
  data: ErrorResponse
  status: 400
}
    
export type postApiAbuseCasesResponseComposite = postApiAbuseCasesResponse200 | postApiAbuseCasesResponse201 | postApiAbuseCasesResponse400;
    
export type postApiAbuseCasesResponse = postApiAbuseCasesResponseComposite & {
  headers: Headers;
}

export const getPostApiAbuseCasesUrl = () => {


  

  return `/api/api/abuse/cases`
}

export const postApiAbuseCases = async (createCaseRequest: CreateCaseRequest, options?: RequestInit): Promise<postApiAbuseCasesResponse> => {
  
  const res = await fetch(getPostApiAbuseCasesUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createCaseRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: postApiAbuseCasesResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as postApiAbuseCasesResponse
}


/**
 * Retrieves a specific abuse case by ID
 * @summary Get Case
 */
export type getApiAbuseCasesIdResponse200 = {
  data: CaseResponse
  status: 200
}

export type getApiAbuseCasesIdResponse400 = {
  data: ErrorResponse
  status: 400
}
    
export type getApiAbuseCasesIdResponseComposite = getApiAbuseCasesIdResponse200 | getApiAbuseCasesIdResponse400;
    
export type getApiAbuseCasesIdResponse = getApiAbuseCasesIdResponseComposite & {
  headers: Headers;
}

export const getGetApiAbuseCasesIdUrl = (id: number,) => {


  

  return `/api/api/abuse/cases/${id}`
}

export const getApiAbuseCasesId = async (id: number, options?: RequestInit): Promise<getApiAbuseCasesIdResponse> => {
  
  const res = await fetch(getGetApiAbuseCasesIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: getApiAbuseCasesIdResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as getApiAbuseCasesIdResponse
}


/**
 * Updates an existing abuse case by ID
 * @summary Update Case
 */
export type putApiAbuseCasesIdResponse200 = {
  data: CaseResponse
  status: 200
}

export type putApiAbuseCasesIdResponse400 = {
  data: ErrorResponse
  status: 400
}
    
export type putApiAbuseCasesIdResponseComposite = putApiAbuseCasesIdResponse200 | putApiAbuseCasesIdResponse400;
    
export type putApiAbuseCasesIdResponse = putApiAbuseCasesIdResponseComposite & {
  headers: Headers;
}

export const getPutApiAbuseCasesIdUrl = (id: number,) => {


  

  return `/api/api/abuse/cases/${id}`
}

export const putApiAbuseCasesId = async (id: number,
    updateCaseRequest: UpdateCaseRequest, options?: RequestInit): Promise<putApiAbuseCasesIdResponse> => {
  
  const res = await fetch(getPutApiAbuseCasesIdUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateCaseRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: putApiAbuseCasesIdResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as putApiAbuseCasesIdResponse
}


/**
 * Update the status of an abuse case
 * @summary Update case status
 */
export type putApiAbuseCasesIdStatusResponse200 = {
  data: CaseStatusResponse
  status: 200
}

export type putApiAbuseCasesIdStatusResponse400 = {
  data: ErrorResponse
  status: 400
}
    
export type putApiAbuseCasesIdStatusResponseComposite = putApiAbuseCasesIdStatusResponse200 | putApiAbuseCasesIdStatusResponse400;
    
export type putApiAbuseCasesIdStatusResponse = putApiAbuseCasesIdStatusResponseComposite & {
  headers: Headers;
}

export const getPutApiAbuseCasesIdStatusUrl = (id: number,) => {


  

  return `/api/api/abuse/cases/${id}/status`
}

export const putApiAbuseCasesIdStatus = async (id: number,
    caseStatusUpdateRequest: CaseStatusUpdateRequest, options?: RequestInit): Promise<putApiAbuseCasesIdStatusResponse> => {
  
  const res = await fetch(getPutApiAbuseCasesIdStatusUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      caseStatusUpdateRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: putApiAbuseCasesIdStatusResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as putApiAbuseCasesIdStatusResponse
}


