/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Portal Admin API
 * Provides administrative endpoints for managing the Portal.
 * OpenAPI spec version: unknown
 */
import type {
  CommunicationCreateRequest,
  CommunicationResponse,
  ErrorResponse
} from './portalAdminAPI.schemas';



/**
 * Add a new communication to a case
 * @summary Add case communication
 */
export type postApiAbuseCasesIdCommunicationsResponse200 = {
  data: ErrorResponse
  status: 200
}

export type postApiAbuseCasesIdCommunicationsResponse201 = {
  data: CommunicationResponse
  status: 201
}

export type postApiAbuseCasesIdCommunicationsResponse400 = {
  data: ErrorResponse
  status: 400
}
    
export type postApiAbuseCasesIdCommunicationsResponseComposite = postApiAbuseCasesIdCommunicationsResponse200 | postApiAbuseCasesIdCommunicationsResponse201 | postApiAbuseCasesIdCommunicationsResponse400;
    
export type postApiAbuseCasesIdCommunicationsResponse = postApiAbuseCasesIdCommunicationsResponseComposite & {
  headers: Headers;
}

export const getPostApiAbuseCasesIdCommunicationsUrl = (id: number,) => {


  

  return `/api/api/abuse/cases/${id}/communications`
}

export const postApiAbuseCasesIdCommunications = async (id: number,
    communicationCreateRequest: CommunicationCreateRequest, options?: RequestInit): Promise<postApiAbuseCasesIdCommunicationsResponse> => {
  
  const res = await fetch(getPostApiAbuseCasesIdCommunicationsUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      communicationCreateRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: postApiAbuseCasesIdCommunicationsResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as postApiAbuseCasesIdCommunicationsResponse
}


