/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Portal Admin API
 * Provides administrative endpoints for managing the Portal.
 * OpenAPI spec version: unknown
 */
import type {
  ErrorResponse,
  EvidenceResponse,
  GetApiAbuseEvidenceIdContent200,
  PostApiAbuseCasesIdEvidenceBody
} from './portalAdminAPI.schemas';



/**
 * Uploads a file as evidence for a specific case
 * @summary Upload evidence file
 */
export type postApiAbuseCasesIdEvidenceResponse200 = {
  data: ErrorResponse
  status: 200
}

export type postApiAbuseCasesIdEvidenceResponse201 = {
  data: EvidenceResponse
  status: 201
}

export type postApiAbuseCasesIdEvidenceResponse400 = {
  data: ErrorResponse
  status: 400
}
    
export type postApiAbuseCasesIdEvidenceResponseComposite = postApiAbuseCasesIdEvidenceResponse200 | postApiAbuseCasesIdEvidenceResponse201 | postApiAbuseCasesIdEvidenceResponse400;
    
export type postApiAbuseCasesIdEvidenceResponse = postApiAbuseCasesIdEvidenceResponseComposite & {
  headers: Headers;
}

export const getPostApiAbuseCasesIdEvidenceUrl = (id: number,) => {


  

  return `/api/api/abuse/cases/${id}/evidence`
}

export const postApiAbuseCasesIdEvidence = async (id: number,
    postApiAbuseCasesIdEvidenceBody: PostApiAbuseCasesIdEvidenceBody, options?: RequestInit): Promise<postApiAbuseCasesIdEvidenceResponse> => {
    const formData = new FormData();
formData.append(`file`, postApiAbuseCasesIdEvidenceBody.file)

  const res = await fetch(getPostApiAbuseCasesIdEvidenceUrl(id),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: postApiAbuseCasesIdEvidenceResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as postApiAbuseCasesIdEvidenceResponse
}


/**
 * Retrieve metadata for a specific evidence item by ID
 * @summary Get evidence metadata
 */
export type getApiAbuseEvidenceIdResponse200 = {
  data: EvidenceResponse
  status: 200
}

export type getApiAbuseEvidenceIdResponse400 = {
  data: ErrorResponse
  status: 400
}
    
export type getApiAbuseEvidenceIdResponseComposite = getApiAbuseEvidenceIdResponse200 | getApiAbuseEvidenceIdResponse400;
    
export type getApiAbuseEvidenceIdResponse = getApiAbuseEvidenceIdResponseComposite & {
  headers: Headers;
}

export const getGetApiAbuseEvidenceIdUrl = (id: number,) => {


  

  return `/api/api/abuse/evidence/${id}`
}

export const getApiAbuseEvidenceId = async (id: number, options?: RequestInit): Promise<getApiAbuseEvidenceIdResponse> => {
  
  const res = await fetch(getGetApiAbuseEvidenceIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: getApiAbuseEvidenceIdResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as getApiAbuseEvidenceIdResponse
}


/**
 * Retrieve the content of a specific evidence item by ID
 * @summary Get evidence content
 */
export type getApiAbuseEvidenceIdContentResponse200 = {
  data: GetApiAbuseEvidenceIdContent200
  status: 200
}

export type getApiAbuseEvidenceIdContentResponse400 = {
  data: ErrorResponse
  status: 400
}
    
export type getApiAbuseEvidenceIdContentResponseComposite = getApiAbuseEvidenceIdContentResponse200 | getApiAbuseEvidenceIdContentResponse400;
    
export type getApiAbuseEvidenceIdContentResponse = getApiAbuseEvidenceIdContentResponseComposite & {
  headers: Headers;
}

export const getGetApiAbuseEvidenceIdContentUrl = (id: number,) => {


  

  return `/api/api/abuse/evidence/${id}/content`
}

export const getApiAbuseEvidenceIdContent = async (id: number, options?: RequestInit): Promise<getApiAbuseEvidenceIdContentResponse> => {
  
  const res = await fetch(getGetApiAbuseEvidenceIdContentUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: getApiAbuseEvidenceIdContentResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as getApiAbuseEvidenceIdContentResponse
}


