/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Portal Admin API
 * Provides administrative endpoints for managing the Portal.
 * OpenAPI spec version: unknown
 */
export interface CommunicationResponse {
  content: string;
  created_at: string;
  direction: string;
  id: number;
  parent_id?: number;
  type: string;
  updated_at: string;
}

export interface GlobalSearchResponse {
  cases: CaseResponse[];
  reporters: ReporterResponse[];
  total_count: number;
}

export interface ReporterResponse {
  created_at: string;
  email: string;
  id: number;
  name: string;
  updated_at: string;
}

export interface CaseResponse {
  communications?: CommunicationResponse[];
  created_at: string;
  description: string;
  id: number;
  needs_review: boolean;
  priority: string;
  reference_number: string;
  reporter_id: number;
  scans?: ScanResponse[];
  source: string;
  status: string;
  subject_id: number;
  type: string;
  updated_at: string;
}

export interface ScanResponse {
  case_id: number;
  completed_at?: string;
  created_at: string;
  id: number;
  scheduled_at: string;
  started_at?: string;
  status: string;
  subject_id: number;
  updated_at: string;
}

export interface CaseStatusUpdateRequest {
  status: string;
}

export interface ErrorResponse {
  error: string;
}

export interface SubjectCreateRequest {
  identifier: string;
  type: string;
}

export interface CaseTypeSourceMatrixResponse {
  items: CaseTypeSourceMatrixItemResponse[];
}

export interface CaseTypeSourceMatrixItemResponse {
  case_count: number;
  case_date: string;
  case_type: string;
  report_source: string;
}

export interface StatusFlowGraph {
  links: StatusFlowLink[];
  nodes: StatusFlowNode[];
}

export interface StatusFlowLink {
  source: string;
  target: string;
  value: number;
}

export interface StatusFlowNode {
  name: string;
}

export interface SubjectResponse {
  created_at: string;
  id: number;
  identifier: string;
  updated_at: string;
}

export interface CaseAnalyticsResponse {
  avg_status_durations: DurationDistribution[];
  blocklist: BlocklistMetrics;
  case_type_distribution: Distribution[];
  communications: CommunicationsMetrics;
  evidence: EvidenceMetrics;
  needs_review_count: number;
  new_cases: number;
  open_cases: number;
  resolution_metrics: ResolutionMetrics;
  source_distribution: Distribution[];
  status_distribution: Distribution[];
  status_durations: DurationDistribution[];
  total_cases: number;
}

export interface EvidenceMetrics {
  average_per_case: number;
  files_per_case: Distribution[];
}

export interface Distribution {
  count: number;
  name: string;
}

export interface BlocklistMetrics {
  by_reason: Distribution[];
  by_severity: Distribution[];
  total_blocks: number;
}

export interface CommunicationsMetrics {
  average_response_seconds: number;
  counts_per_case: Distribution[];
  max_response_seconds: number;
}

export interface DurationDistribution {
  duration_seconds: number;
  status: string;
}

export interface ResolutionMetrics {
  average_seconds: number;
  daily_trends: ResolutionTrend[];
}

export interface ResolutionTrend {
  average_seconds: number;
  date: string;
  resolved_count: number;
}

export interface CommunicationCreateRequest {
  content: string;
  direction: string;
  parent_id?: number;
  type: string;
}

export interface CaseStatusResponse {
  created_at: string;
  id: number;
  new_status: string;
  old_status: string;
  updated_at: string;
}

export interface UpdateCaseRequest {
  description: string;
  needs_review?: boolean;
  priority?: string;
  reporter_id?: number;
  source?: string;
  subject_id?: number;
  type?: string;
}

export type BlockContentResponseMetadata = { [key: string]: unknown };

export interface BlockContentResponse {
  action: string;
  blocked_by: number;
  case_id?: number;
  created_at: string;
  description?: string;
  expires_at?: string;
  file_name?: string;
  hash: string;
  id: number;
  metadata?: BlockContentResponseMetadata;
  mime_type?: string;
  reason: string;
  reviewed_at?: string;
  severity: string;
  size?: number;
  source?: string;
  updated_at: string;
  uploader_id?: number;
}

export type EvidenceResponseMetadata = { [key: string]: unknown };

export interface EvidenceResponse {
  case_id: number;
  content_type: string;
  created_at: string;
  description: string;
  file_name: string;
  file_size: number;
  id: number;
  metadata: EvidenceResponseMetadata;
  source: string;
  storage_hash: string;
  submitter_id: number;
  updated_at: string;
}

export interface ReporterCreateRequest {
  email: string;
  name: string;
}

export interface BlockContentCreateRequest {
  action: string;
  case_id?: number;
  description?: string;
  expires_at?: string;
  file_name?: string;
  hash: string;
  metadata?: string;
  mime_type?: string;
  reason: string;
  severity: string;
  size?: number;
  source?: string;
  uploader_id?: number;
}

export interface ManualScanRequest {
  case_id: number;
}

export interface BlockReasonListResponse {
  items: BlockReasonCountResponse[];
}

export interface BlockReasonCountResponse {
  block_date: string;
  count: number;
  reason: string;
}

export interface CommunicationTimelineResponse {
  items: CommunicationTimelineItem[];
}

export interface CommunicationTimelineItem {
  count: number;
  hourly_interval: string;
}

export interface CreateCaseRequest {
  description: string;
  needs_review: boolean;
  priority: string;
  reporter_id: number;
  source: string;
  subject_id: number;
  type: string;
}

export type GetApiAbuseAnalyticsBlocklistBlockReasonsParams = {
/**
 * Time range
 */
time_range?: { [key: string]: unknown };
};

export type GetApiAbuseAnalyticsCasesParams = {
/**
 * Ending index of the items to return (exclusive). Defaults to 10.
 */
_end?: number;
/**
 * Starting index of the items to return (0-based). Defaults to 0.
 */
_start?: number;
};

export type GetApiAbuseAnalyticsCasesStatusFlowParams = {
/**
 * Time range
 */
time_range?: { [key: string]: unknown };
};

export type GetApiAbuseAnalyticsCasesTimeSeriesParams = {
/**
 * Filter by case type
 */
case_type?: string[];
/**
 * Metric to retrieve
 */
metric?: { [key: string]: unknown };
/**
 * Filter by priority
 */
priority?: string[];
/**
 * Time range
 */
time_range?: { [key: string]: unknown };
};

export type GetApiAbuseAnalyticsCasesTypeSourceMatrixParams = {
/**
 * Time range
 */
time_range?: { [key: string]: unknown };
};

export type GetApiAbuseAnalyticsCommunicationsTimelineParams = {
/**
 * Time range
 */
time_range?: { [key: string]: unknown };
};

export type GetApiAbuseBlocklistParams = {
/**
 * Ending index of the items to return (exclusive). Defaults to 10.
 */
_end?: number;
/**
 * Starting index of the items to return (0-based). Defaults to 0.
 */
_start?: number;
/**
 * Global search query string.
 */
q?: string;
};

export type GetApiAbuseCasesParams = {
/**
 * Ending index of the items to return (exclusive). Defaults to 10.
 */
_end?: number;
/**
 * Starting index of the items to return (0-based). Defaults to 0.
 */
_start?: number;
/**
 * Global search query string.
 */
q?: string;
};

export type GetApiAbuseCases200 = { [key: string]: unknown };

export type GetApiAbuseCasesCaseIdScansParams = {
/**
 * Ending index of the items to return (exclusive). Defaults to 10.
 */
_end?: number;
/**
 * Starting index of the items to return (0-based). Defaults to 0.
 */
_start?: number;
/**
 * Global search query string.
 */
q?: string;
};

export type PostApiAbuseCasesCaseIdScans202 = {[key: string]: string};

export type GetApiAbuseCasesCaseIdScansScanIdResultsParams = {
/**
 * Ending index of the items to return (exclusive). Defaults to 10.
 */
_end?: number;
/**
 * Starting index of the items to return (0-based). Defaults to 0.
 */
_start?: number;
/**
 * Global search query string.
 */
q?: string;
};

export type GetApiAbuseCasesIdCommunicationsParams = {
/**
 * Ending index of the items to return (exclusive). Defaults to 10.
 */
_end?: number;
/**
 * Starting index of the items to return (0-based). Defaults to 0.
 */
_start?: number;
/**
 * Global search query string.
 */
q?: string;
};

export type GetApiAbuseCasesIdEvidenceParams = {
/**
 * Ending index of the items to return (exclusive). Defaults to 10.
 */
_end?: number;
/**
 * Starting index of the items to return (0-based). Defaults to 0.
 */
_start?: number;
/**
 * Global search query string.
 */
q?: string;
};

export type PostApiAbuseCasesIdEvidenceBody = {
  file: string;
};

export type GetApiAbuseEvidenceIdContent200 = { [key: string]: unknown };

export type GetApiAbuseReportersParams = {
/**
 * Ending index of the items to return (exclusive). Defaults to 10.
 */
_end?: number;
/**
 * Starting index of the items to return (0-based). Defaults to 0.
 */
_start?: number;
/**
 * Global search query string.
 */
q?: string;
};

export type GetApiAbuseSearchCasesParams = {
/**
 * Ending index of the items to return (exclusive). Defaults to 10.
 */
_end?: number;
/**
 * Starting index of the items to return (0-based). Defaults to 0.
 */
_start?: number;
/**
 * Global search query string.
 */
q?: string;
};

export type GetApiAbuseSearchGlobalParams = {
/**
 * Ending index of the items to return (exclusive). Defaults to 10.
 */
_end?: number;
/**
 * Starting index of the items to return (0-based). Defaults to 0.
 */
_start?: number;
/**
 * Global search query string.
 */
q?: string;
};

export type GetApiAbuseSubjectsParams = {
/**
 * Ending index of the items to return (exclusive). Defaults to 10.
 */
_end?: number;
/**
 * Starting index of the items to return (0-based). Defaults to 0.
 */
_start?: number;
/**
 * Global search query string.
 */
q?: string;
};

