/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Portal Admin API
 * Provides administrative endpoints for managing the Portal.
 * OpenAPI spec version: unknown
 */
import type {
  ErrorResponse,
  ReporterCreateRequest,
  ReporterResponse
} from './portalAdminAPI.schemas';



/**
 * Create a new reporter
 * @summary Create reporter
 */
export type postApiAbuseReportersResponse200 = {
  data: ErrorResponse
  status: 200
}

export type postApiAbuseReportersResponse201 = {
  data: ReporterResponse
  status: 201
}

export type postApiAbuseReportersResponse400 = {
  data: ErrorResponse
  status: 400
}
    
export type postApiAbuseReportersResponseComposite = postApiAbuseReportersResponse200 | postApiAbuseReportersResponse201 | postApiAbuseReportersResponse400;
    
export type postApiAbuseReportersResponse = postApiAbuseReportersResponseComposite & {
  headers: Headers;
}

export const getPostApiAbuseReportersUrl = () => {


  

  return `/api/api/abuse/reporters`
}

export const postApiAbuseReporters = async (reporterCreateRequest: ReporterCreateRequest, options?: RequestInit): Promise<postApiAbuseReportersResponse> => {
  
  const res = await fetch(getPostApiAbuseReportersUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      reporterCreateRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: postApiAbuseReportersResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as postApiAbuseReportersResponse
}


/**
 * Retrieve a specific reporter by ID
 * @summary Get reporter
 */
export type getApiAbuseReportersIdResponse200 = {
  data: ReporterResponse
  status: 200
}

export type getApiAbuseReportersIdResponse400 = {
  data: ErrorResponse
  status: 400
}
    
export type getApiAbuseReportersIdResponseComposite = getApiAbuseReportersIdResponse200 | getApiAbuseReportersIdResponse400;
    
export type getApiAbuseReportersIdResponse = getApiAbuseReportersIdResponseComposite & {
  headers: Headers;
}

export const getGetApiAbuseReportersIdUrl = (id: number,) => {


  

  return `/api/api/abuse/reporters/${id}`
}

export const getApiAbuseReportersId = async (id: number, options?: RequestInit): Promise<getApiAbuseReportersIdResponse> => {
  
  const res = await fetch(getGetApiAbuseReportersIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: getApiAbuseReportersIdResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as getApiAbuseReportersIdResponse
}


