/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Portal Admin API
 * Provides administrative endpoints for managing the Portal.
 * OpenAPI spec version: unknown
 */
import type {
  ErrorResponse,
  ManualScanRequest,
  PostApiAbuseCasesCaseIdScans202,
  ScanResponse
} from './portalAdminAPI.schemas';



/**
 * Initiates a scan for the subject associated with the case.
 * @summary Create scan request for case subject
 */
export type postApiAbuseCasesCaseIdScansResponse200 = {
  data: ErrorResponse
  status: 200
}

export type postApiAbuseCasesCaseIdScansResponse202 = {
  data: PostApiAbuseCasesCaseIdScans202
  status: 202
}

export type postApiAbuseCasesCaseIdScansResponse400 = {
  data: ErrorResponse
  status: 400
}
    
export type postApiAbuseCasesCaseIdScansResponseComposite = postApiAbuseCasesCaseIdScansResponse200 | postApiAbuseCasesCaseIdScansResponse202 | postApiAbuseCasesCaseIdScansResponse400;
    
export type postApiAbuseCasesCaseIdScansResponse = postApiAbuseCasesCaseIdScansResponseComposite & {
  headers: Headers;
}

export const getPostApiAbuseCasesCaseIdScansUrl = (caseId: number,) => {


  

  return `/api/api/abuse/cases/${caseId}/scans`
}

export const postApiAbuseCasesCaseIdScans = async (caseId: number,
    manualScanRequest: ManualScanRequest, options?: RequestInit): Promise<postApiAbuseCasesCaseIdScansResponse> => {
  
  const res = await fetch(getPostApiAbuseCasesCaseIdScansUrl(caseId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      manualScanRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: postApiAbuseCasesCaseIdScansResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as postApiAbuseCasesCaseIdScansResponse
}


/**
 * Retrieve details of a specific scan
 * @summary Get scan
 */
export type getApiAbuseCasesCaseIdScansScanIdResponse200 = {
  data: ScanResponse
  status: 200
}

export type getApiAbuseCasesCaseIdScansScanIdResponse400 = {
  data: ErrorResponse
  status: 400
}
    
export type getApiAbuseCasesCaseIdScansScanIdResponseComposite = getApiAbuseCasesCaseIdScansScanIdResponse200 | getApiAbuseCasesCaseIdScansScanIdResponse400;
    
export type getApiAbuseCasesCaseIdScansScanIdResponse = getApiAbuseCasesCaseIdScansScanIdResponseComposite & {
  headers: Headers;
}

export const getGetApiAbuseCasesCaseIdScansScanIdUrl = (caseId: number,
    scanId: number,) => {


  

  return `/api/api/abuse/cases/${caseId}/scans/${scanId}`
}

export const getApiAbuseCasesCaseIdScansScanId = async (caseId: number,
    scanId: number, options?: RequestInit): Promise<getApiAbuseCasesCaseIdScansScanIdResponse> => {
  
  const res = await fetch(getGetApiAbuseCasesCaseIdScansScanIdUrl(caseId,scanId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: getApiAbuseCasesCaseIdScansScanIdResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as getApiAbuseCasesCaseIdScansScanIdResponse
}


