/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Portal Admin API
 * Provides administrative endpoints for managing the Portal.
 * OpenAPI spec version: unknown
 */
import type {
  ErrorResponse,
  GetApiAbuseSearchGlobalParams,
  GlobalSearchResponse
} from './portalAdminAPI.schemas';



/**
 * Search across multiple entities (cases, reporters) by query string with pagination
 * @summary Global search
 */
export type getApiAbuseSearchGlobalResponse200 = {
  data: GlobalSearchResponse
  status: 200
}

export type getApiAbuseSearchGlobalResponse400 = {
  data: ErrorResponse
  status: 400
}
    
export type getApiAbuseSearchGlobalResponseComposite = getApiAbuseSearchGlobalResponse200 | getApiAbuseSearchGlobalResponse400;
    
export type getApiAbuseSearchGlobalResponse = getApiAbuseSearchGlobalResponseComposite & {
  headers: Headers;
}

export const getGetApiAbuseSearchGlobalUrl = (params?: GetApiAbuseSearchGlobalParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/api/abuse/search/global?${stringifiedParams}` : `/api/api/abuse/search/global`
}

export const getApiAbuseSearchGlobal = async (params?: GetApiAbuseSearchGlobalParams, options?: RequestInit): Promise<getApiAbuseSearchGlobalResponse> => {
  
  const res = await fetch(getGetApiAbuseSearchGlobalUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: getApiAbuseSearchGlobalResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as getApiAbuseSearchGlobalResponse
}


