/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Portal Admin API
 * Provides administrative endpoints for managing the Portal.
 * OpenAPI spec version: unknown
 */
import type {
  ErrorResponse,
  SubjectCreateRequest,
  SubjectResponse
} from './portalAdminAPI.schemas';



/**
 * Create a new subject
 * @summary Create subject
 */
export type postApiAbuseSubjectsResponse200 = {
  data: ErrorResponse
  status: 200
}

export type postApiAbuseSubjectsResponse201 = {
  data: SubjectResponse
  status: 201
}

export type postApiAbuseSubjectsResponse400 = {
  data: ErrorResponse
  status: 400
}
    
export type postApiAbuseSubjectsResponseComposite = postApiAbuseSubjectsResponse200 | postApiAbuseSubjectsResponse201 | postApiAbuseSubjectsResponse400;
    
export type postApiAbuseSubjectsResponse = postApiAbuseSubjectsResponseComposite & {
  headers: Headers;
}

export const getPostApiAbuseSubjectsUrl = () => {


  

  return `/api/api/abuse/subjects`
}

export const postApiAbuseSubjects = async (subjectCreateRequest: SubjectCreateRequest, options?: RequestInit): Promise<postApiAbuseSubjectsResponse> => {
  
  const res = await fetch(getPostApiAbuseSubjectsUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      subjectCreateRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: postApiAbuseSubjectsResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as postApiAbuseSubjectsResponse
}


/**
 * Retrieve a specific subject by ID
 * @summary Get subject
 */
export type getApiAbuseSubjectsIdResponse200 = {
  data: SubjectResponse
  status: 200
}

export type getApiAbuseSubjectsIdResponse400 = {
  data: ErrorResponse
  status: 400
}
    
export type getApiAbuseSubjectsIdResponseComposite = getApiAbuseSubjectsIdResponse200 | getApiAbuseSubjectsIdResponse400;
    
export type getApiAbuseSubjectsIdResponse = getApiAbuseSubjectsIdResponseComposite & {
  headers: Headers;
}

export const getGetApiAbuseSubjectsIdUrl = (id: number,) => {


  

  return `/api/api/abuse/subjects/${id}`
}

export const getApiAbuseSubjectsId = async (id: number, options?: RequestInit): Promise<getApiAbuseSubjectsIdResponse> => {
  
  const res = await fetch(getGetApiAbuseSubjectsIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: getApiAbuseSubjectsIdResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as getApiAbuseSubjectsIdResponse
}


