version: '3.8'
services:
    app:
        image: git.lumeweb.com/lumeweb/web3.news:latest
        ports:
            - "3000:3000"
        volumes:
            - ./data/app.db:/app/prisma/dev.db
    bridge:
        image: git.lumeweb.com/lumeweb/web3.news:latest
        command: ["npm", "run", "bridge"]
        volumes:
            - ./data/app.db:/app/prisma/dev.db
    melli:
        image: getmeili/meilisearch:v1.5
        volumes:
            - ./melli_data:/meili_data
    melli_init:
        image: git.lumeweb.com/lumeweb/web3.news:latest
        command: ["npm", "run", "melli-init"]
        volumes:
            - ./data/app.db:/app/prisma/dev.db
        profiles: ["disabled"]
    db_init:
        image: git.lumeweb.com/lumeweb/web3.news:latest
        command: ["npm", "run", "db-init"]
        volumes:
            - ./data/app.db:/app/prisma/dev.db
        profiles: ["disabled"]
