packages:
  - apps/*
  - libs/*

catalog:
  '@astrojs/react': ^5.0.4
  '@conform-to/react': ^1.19.0
  '@helia/car': ^5.4.2
  '@helia/http': ^3.1.4
  '@helia/unixfs': ^7.2.1
  '@hookform/resolvers': 5.2.2
  '@ipfs-shipyard/pinning-service-client': ^3.0.0
  '@ipld/car': ^5.4.3
  '@module-federation/vite': ^1.14.5
  '@mswjs/interceptors': ^0.41.6
  '@radix-ui/react-dropdown-menu': ^2.1.16
  '@radix-ui/react-icons': ^1.3.2
  '@radix-ui/react-navigation-menu': ^1.2.14
  '@radix-ui/react-progress': ^1.1.8
  '@radix-ui/react-slot': ^1.2.4
  '@refinedev/core': ^5.0.12
  '@refinedev/react-hook-form': ^5.0.4
  '@refinedev/react-router': ^2.0.4
  '@refinedev/react-table': ^6.0.1
  '@t3-oss/env-core': ^0.13.11
  '@tailwindcss/vite': ^4.2.4
  '@tanstack/react-query': ^5.100.5
  '@tanstack/react-table': ^8.21.3
  '@turbo/gen': ^2.9.6
  '@types/node': ^25.6.0
  '@types/react': ^19.2.14
  '@types/react-dom': ^19.2.3
  '@uppy/core': ^5.2.0
  '@uppy/tus': 5.1.0
  '@uppy/xhr-upload': 5.1.1
  '@vitest/browser-playwright': ^4.1.5
  astro: ^6.1.9
  blockstore-core: ^6.1.3
  blockstore-idb: ^3.0.2
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  datastore-core: ^11.0.4
  datastore-idb: ^4.0.3
  date-fns: ^4.1.0
  dotenv-cli: ^11.0.0
  happy-dom: ^20.9.0
  ky: ^2.0.2
  lucide-react: ^1.11.0
  msw: ^2.13.6
  multiformats: ^13.4.2
  nanoevents: ^9.1.0
  nock: ^14.0.13
  npm-run-all: ^4.1.5
  orval: ^8.8.1
  otpauth: ^9.5.1
  playwright: ^1.59.1
  progress-events: ^1.1.0
  qrcode: ^1.5.4
  react: ^19.2.5
  react-dom: ^19.2.5
  react-hook-form: ^7.74.0
  react-icons: ^5.6.0
  react-is: ^19.1.6
  react-router: ^7.14.2
  recharts: ^3.8.1
  tailwind-merge: ^3.5.0
  tailwindcss: ^3.4.19
  tailwindcss-animate: ^1.0.7
  tsdown: v0.20.0-beta.4
  typescript: ^6.0.3
  vite: 7.1.11
  vite-tsconfig-paths: ^6.1.1
  vitest: ^4.1.5
  vocs: ^1.4.1
  zod: ^4.3.6

catalogs:
  framework:
    vite: ^6.4.1
    zod: ^4.3.6
  websites:
    tailwindcss: ^4.1.18

gitChecks: false

publishBranch: develop
