/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Abuse Report API
 * Public API for user submission and tracking of abuse reports.
 * OpenAPI spec version: develop
 */
export interface AbuseReportRequest {
  abuse_type: string;
  additional_details?: string;
  description: string;
  email: string;
  location: string;
}

export interface AbuseReportResponse {
  access_token?: string;
  case_reference: string;
  expires_at?: string;
  received_at?: string;
}

export interface AttachmentUploadResponse {
  content_type: string;
  filename: string;
  message: string;
  size: number;
}

export interface CommunicationResponse {
  content: string;
  created_at: string;
  direction: string;
  id: number;
  parent_id?: number;
  type: string;
  updated_at: string;
}

export type EvidenceResponseMetadata = { [key: string]: unknown };

export interface EvidenceResponse {
  case_id: number;
  content_type: string;
  created_at: string;
  description: string;
  file_name: string;
  file_size: number;
  id: number;
  metadata: EvidenceResponseMetadata;
  source: string;
  storage_hash: string;
  submitter_id: number;
  updated_at: string;
}

export interface JWTResponse {
  access_token: string;
  expires_at: string;
}

export interface PublicCaseResponse {
  attachments?: EvidenceResponse[];
  communications?: CommunicationResponse[];
  created_at: string;
  description: string;
  reference_number: string;
  scans?: ScanResponse[];
  status: string;
  type: string;
  updated_at: string;
}

export interface ResponseError {
  error: string;
}

export interface ScanResponse {
  case_id: number;
  completed_at?: string;
  created_at: string;
  id: number;
  scheduled_at: string;
  started_at?: string;
  status: string;
  subject_id: number;
  updated_at: string;
}

export interface TokenRefreshRequest {
  token: string;
}

export interface TokenRefreshResponse {
  token: string;
  valid_days: number;
}

export interface ValidateTokenResponse {
  reference: string;
  valid: boolean;
}

export type PostApiCasesReferenceAttachmentsBody = {
  file: string;
};

export type PostApiCasesReferenceAttachments200 = {[key: string]: string};

export type PostApiCasesReferenceCommunicationsBody = {
  Content: string;
};

export type PostApiCasesReferenceCommunications200 = {[key: string]: string};

export type PostApiReports200 = {[key: string]: string};

