/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Abuse Report API
 * Public API for user submission and tracking of abuse reports.
 * OpenAPI spec version: develop
 */
import type {
  AbuseReportRequest,
  AbuseReportResponse,
  AttachmentUploadResponse,
  CommunicationResponse,
  JWTResponse,
  PostApiCasesReferenceAttachments200,
  PostApiCasesReferenceAttachmentsBody,
  PostApiCasesReferenceCommunications200,
  PostApiCasesReferenceCommunicationsBody,
  PostApiReports200,
  PublicCaseResponse,
  ResponseError,
  TokenRefreshRequest,
  TokenRefreshResponse,
  ValidateTokenResponse
} from './abuseReportAPI.schemas';



/**
 * Retrieves the details of a specific abuse case, including communications, scans, and evidence.
 * @summary Get abuse case details
 */
export type getApiCasesReferenceResponse200 = {
  data: PublicCaseResponse
  status: 200
}

export type getApiCasesReferenceResponse400 = {
  data: ResponseError
  status: 400
}
    
export type getApiCasesReferenceResponseComposite = getApiCasesReferenceResponse200 | getApiCasesReferenceResponse400;
    
export type getApiCasesReferenceResponse = getApiCasesReferenceResponseComposite & {
  headers: Headers;
}

export const getGetApiCasesReferenceUrl = (reference: string,) => {


  

  return `/api/api/cases/${reference}`
}

export const getApiCasesReference = async (reference: string, options?: RequestInit): Promise<getApiCasesReferenceResponse> => {
  
  const res = await fetch(getGetApiCasesReferenceUrl(reference),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: getApiCasesReferenceResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as getApiCasesReferenceResponse
}


/**
 * Uploads a file attachment as evidence for a specific abuse case.
 * @summary Upload an attachment to an abuse case
 */
export type postApiCasesReferenceAttachmentsResponse200 = {
  data: PostApiCasesReferenceAttachments200
  status: 200
}

export type postApiCasesReferenceAttachmentsResponse201 = {
  data: AttachmentUploadResponse
  status: 201
}

export type postApiCasesReferenceAttachmentsResponse400 = {
  data: ResponseError
  status: 400
}
    
export type postApiCasesReferenceAttachmentsResponseComposite = postApiCasesReferenceAttachmentsResponse200 | postApiCasesReferenceAttachmentsResponse201 | postApiCasesReferenceAttachmentsResponse400;
    
export type postApiCasesReferenceAttachmentsResponse = postApiCasesReferenceAttachmentsResponseComposite & {
  headers: Headers;
}

export const getPostApiCasesReferenceAttachmentsUrl = (reference: string,) => {


  

  return `/api/api/cases/${reference}/attachments`
}

export const postApiCasesReferenceAttachments = async (reference: string,
    postApiCasesReferenceAttachmentsBody: PostApiCasesReferenceAttachmentsBody, options?: RequestInit): Promise<postApiCasesReferenceAttachmentsResponse> => {
    const formData = new FormData();
formData.append(`file`, postApiCasesReferenceAttachmentsBody.file)

  const res = await fetch(getPostApiCasesReferenceAttachmentsUrl(reference),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: postApiCasesReferenceAttachmentsResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as postApiCasesReferenceAttachmentsResponse
}


/**
 * Adds a new communication (comment) to a specific abuse case.
 * @summary Add a comment to an abuse case
 */
export type postApiCasesReferenceCommunicationsResponse200 = {
  data: PostApiCasesReferenceCommunications200
  status: 200
}

export type postApiCasesReferenceCommunicationsResponse201 = {
  data: CommunicationResponse
  status: 201
}

export type postApiCasesReferenceCommunicationsResponse400 = {
  data: ResponseError
  status: 400
}
    
export type postApiCasesReferenceCommunicationsResponseComposite = postApiCasesReferenceCommunicationsResponse200 | postApiCasesReferenceCommunicationsResponse201 | postApiCasesReferenceCommunicationsResponse400;
    
export type postApiCasesReferenceCommunicationsResponse = postApiCasesReferenceCommunicationsResponseComposite & {
  headers: Headers;
}

export const getPostApiCasesReferenceCommunicationsUrl = (reference: string,) => {


  

  return `/api/api/cases/${reference}/communications`
}

export const postApiCasesReferenceCommunications = async (reference: string,
    postApiCasesReferenceCommunicationsBody: PostApiCasesReferenceCommunicationsBody, options?: RequestInit): Promise<postApiCasesReferenceCommunicationsResponse> => {
  
  const res = await fetch(getPostApiCasesReferenceCommunicationsUrl(reference),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiCasesReferenceCommunicationsBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: postApiCasesReferenceCommunicationsResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as postApiCasesReferenceCommunicationsResponse
}


/**
 * Allows users to submit a new abuse report with details and attachments.
 * @summary Submit a new abuse report
 */
export type postApiReportsResponse200 = {
  data: PostApiReports200
  status: 200
}

export type postApiReportsResponse201 = {
  data: AbuseReportResponse
  status: 201
}

export type postApiReportsResponse400 = {
  data: ResponseError
  status: 400
}
    
export type postApiReportsResponseComposite = postApiReportsResponse200 | postApiReportsResponse201 | postApiReportsResponse400;
    
export type postApiReportsResponse = postApiReportsResponseComposite & {
  headers: Headers;
}

export const getPostApiReportsUrl = () => {


  

  return `/api/api/reports`
}

export const postApiReports = async (abuseReportRequest: AbuseReportRequest, options?: RequestInit): Promise<postApiReportsResponse> => {
  
  const res = await fetch(getPostApiReportsUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      abuseReportRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: postApiReportsResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as postApiReportsResponse
}


/**
 * Exchanges a valid abuse report access token for a JWT, setting an authentication cookie.
 * @summary Exchange access token for JWT
 */
export type postApiTokensJwtResponse200 = {
  data: JWTResponse
  status: 200
}

export type postApiTokensJwtResponse400 = {
  data: ResponseError
  status: 400
}
    
export type postApiTokensJwtResponseComposite = postApiTokensJwtResponse200 | postApiTokensJwtResponse400;
    
export type postApiTokensJwtResponse = postApiTokensJwtResponseComposite & {
  headers: Headers;
}

export const getPostApiTokensJwtUrl = () => {


  

  return `/api/api/tokens/jwt`
}

export const postApiTokensJwt = async (tokenRefreshRequest: TokenRefreshRequest, options?: RequestInit): Promise<postApiTokensJwtResponse> => {
  
  const res = await fetch(getPostApiTokensJwtUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      tokenRefreshRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: postApiTokensJwtResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as postApiTokensJwtResponse
}


/**
 * Refreshes an existing access token, returning a new token with extended validity.
 * @summary Refresh an abuse report access token
 */
export type postApiTokensRefreshResponse200 = {
  data: TokenRefreshResponse
  status: 200
}

export type postApiTokensRefreshResponse400 = {
  data: ResponseError
  status: 400
}
    
export type postApiTokensRefreshResponseComposite = postApiTokensRefreshResponse200 | postApiTokensRefreshResponse400;
    
export type postApiTokensRefreshResponse = postApiTokensRefreshResponseComposite & {
  headers: Headers;
}

export const getPostApiTokensRefreshUrl = () => {


  

  return `/api/api/tokens/refresh`
}

export const postApiTokensRefresh = async (tokenRefreshRequest: TokenRefreshRequest, options?: RequestInit): Promise<postApiTokensRefreshResponse> => {
  
  const res = await fetch(getPostApiTokensRefreshUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      tokenRefreshRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: postApiTokensRefreshResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as postApiTokensRefreshResponse
}


/**
 * Checks if a given access token is valid and returns the associated case reference.
 * @summary Validate an abuse report access token
 */
export type postApiTokensValidateResponse200 = {
  data: ValidateTokenResponse
  status: 200
}

export type postApiTokensValidateResponse400 = {
  data: ResponseError
  status: 400
}
    
export type postApiTokensValidateResponseComposite = postApiTokensValidateResponse200 | postApiTokensValidateResponse400;
    
export type postApiTokensValidateResponse = postApiTokensValidateResponseComposite & {
  headers: Headers;
}

export const getPostApiTokensValidateUrl = () => {


  

  return `/api/api/tokens/validate`
}

export const postApiTokensValidate = async (tokenRefreshRequest: TokenRefreshRequest, options?: RequestInit): Promise<postApiTokensValidateResponse> => {
  
  const res = await fetch(getPostApiTokensValidateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      tokenRefreshRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: postApiTokensValidateResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as postApiTokensValidateResponse
}


