/**
 * Browser-decodable AVC/AAC fixture contract for the normalized-MP4 MSE check.
 *
 * The normalized-MSE browser suite's *decode acceptance* tests feed a REAL
 * MediaSource the fMP4 that the default pipeline refragments out of a
 * progressive MP4. A fixture qualifies for those tests only when it is
 * GENUINELY browser-decodable in the engines the check must pass:
 *
 *   - AVC/AVC+AAC sample payloads the demuxers actually decode — complete,
 *     consecutive, real frames from a real encode. Not zero-filler, not one
 *     repeated access unit, not hand-assembled "looks valid" bytes (those pass
 *     demuxing but fire `MEDIA_ERR_DECODE` / a fatal SourceBuffer `error` in a
 *     strict engine — precisely the failure that keeps the check from passing).
 *   - a small, complete, moov-first progressive MP4 (ftyp/moov/mdat) with
 *     distinct track ids and every sample fully present (no truncated `mdat`).
 *   - deterministic: bytes are checked in with a pinned sha256 and a
 *     regeneration path that reproduces them.
 *
 * The demo BBB clips cannot satisfy these: they are single-video-track (no
 * AAC) progressive files whose `mdat` is truncated (only the first IDR is
 * recoverable), so the refragmenter returns `no-media-segments` for the whole
 * file; the package's structural `.bin` fixtures carry no decodable bitstreams
 * by design (see `src/__fixtures__/media/README.md`). The committed fixture
 * below is generated by the pinned ffmpeg lavfi recipe in
 * `src/__fixtures__/media/generate-browser-decodable-fixture.mjs`
 * (testsrc2 320x240@30 + sine 44.1 kHz, x264 High@5.0 → `avc1.640032`, AAC-LC
 * → `mp4a.40.2`, moov-first progressive, complete mdat, 2 s — short enough
 * that moov+ftyp classify inside the default 4 KiB probe window). Its bytes
 * are locked by sha256 here and embedded (base64) in the sibling
 * `browser-decodable-fixture-bytes.ts`, which the browser MSE suite imports
 * (browser-safe: no fs/URL).
 *
 * `HAS_BROWSER_DECODABLE_FIXTURE` is `true` only while the real fixture is
 * present and its sha pinned, so the normalized-MSE decode-acceptance tests
 * run for real (they fail RED if the bytes are not actually decodable). This
 * flag pins the TEST bytes, not production detection: whether normalization is
 * authorized at runtime is the worker capability check's decision. Flipping
 * the flag to `false` (or unpinning the sha without replacing the bytes) turns
 * the acceptance tests off again — never a silent pass.
 *
 * Browser-safe by construction (no node imports): the browser MSE suite imports
 * this module to decide whether its decode-acceptance `describe` runs.
 */
import { browserDecodableFixtureBase64 } from './browser-decodable-fixture-bytes.ts';

/** Set to `true` ONLY when the real fixture is generated + committed (see the script). */
export const HAS_BROWSER_DECODABLE_FIXTURE = true;

/**
 * sha256 of the committed `browser-decodable-avc-aac.mp4`. Regenerate on a
 * pinned toolchain with
 * `node src/__fixtures__/media/generate-browser-decodable-fixture.mjs --generate --emit-bytes-ts`
 * and carry the NEW hash here AND into
 * `browser-decodable-fixture-contract.spec.ts` — a mismatch (bytes present but
 * hash unpinned, or pinned hash not matching the committed file) fails RED.
 */
export const BROWSER_DECODABLE_FIXTURE_SHA256 =
  'd8d8db6b4b73d1c96c3d8eba636f441d68e83ff820ddc84dde5be8aea388f55a';

/** Documented presentation duration (seconds) of the real fixture (2 s at 30 fps / 44.1 kHz). */
export const BROWSER_DECODABLE_FIXTURE_DURATION_SECONDS = 2;

/**
 * Codec-qualified fMP4 MIME the refragmented real fixture carries. Matches the
 * generated bytes' real avcC exactly (avc1.640032 = High profile, level_idc
 * 0x32 @5.0) and the synthetic fixture's BBB avcC, so strict engines
 * (Chromium) accept the append without a declared-MIME vs stream-codec
 * mismatch.
 */
export const BROWSER_DECODABLE_FIXTURE_MIME = 'video/mp4; codecs="avc1.640032,mp4a.40.2"';

/** Expected byte length of the committed fixture (integrity tripwire, not a substitute for the sha). */
const BROWSER_DECODABLE_FIXTURE_BYTE_LENGTH = 102940;

/**
 * Returns the committed real fixture bytes (decoded from the generated
 * browser-safe base64 module). Throws if the embedded module is missing or
 * does not carry the pinned length — the contract's way of refusing to
 * fabricate bytes.
 */
export function browserDecodableFixtureBytes(): Uint8Array {
  const bytes = decodeBase64(browserDecodableFixtureBase64());
  if (bytes.byteLength !== BROWSER_DECODABLE_FIXTURE_BYTE_LENGTH) {
    throw new Error(gapMessage());
  }
  return bytes;
}

function decodeBase64(base64: string): Uint8Array {
  const binary = globalThis.atob(base64);
  const out = new Uint8Array(binary.length);
  for (let index = 0; index < binary.length; index += 1) out[index] = binary.charCodeAt(index);
  return out;
}

function gapMessage(): string {
  return [
    'browserDecodableFixtureBytes() returned bytes whose length does not match',
    `the committed fixture (${BROWSER_DECODABLE_FIXTURE_BYTE_LENGTH} B). Regenerate with`,
    'src/__fixtures__/media/generate-browser-decodable-fixture.mjs --generate --emit-bytes-ts',
    'and re-pin BROWSER_DECODABLE_FIXTURE_SHA256. Never fabricate bytes.',
  ].join(' ');
}
