// Code generated by tools/gencontract — DO NOT EDIT.
// Source: wasm/go/exports/*.go struct json tags
// Regenerate: pnpm --filter @lumeweb/lbry-sdk generate

/**
 * Generic WASM function result.
 * All WASM functions return either a success object or { error: string }.
 */
export type WasmResult<T = Record<string, unknown>> = T | { error: string };

// ── Result Types (guts unavailable, using AST) ──

export interface AddressResult {
  address: string;
}

export interface BuildTxResult {
  txhex: string;
  txid: string;
}

export interface ChannelClaimResult {
  valueHex: string;
}

export interface ClaimIDResult {
  claimIDHex: string;
}

export interface CloseResult {
  closed: boolean;
}

export interface CollectionClaimResult {
  valueHex: string;
}

export interface FeeResult {
  fee: string;
}

export interface MakeSeedResult {
  mnemonic: string;
}

export interface MnemonicResult {
  mnemonic: string;
}

export interface ParsedClaim {
  version: number;
  hasSignature: boolean;
  claimType: string;
  title: string;
  publicKeyHex?: string;
  mediaType?: string;
  sdHashHex?: string;
  claimIDHex?: string;
  signatureHex?: string;
}

export interface PrivateKeyResult {
  privateKey: string;
}

export interface PublicKeyResult {
  publicKey: string;
}

export interface RepostClaimResult {
  valueHex: string;
}

export interface ScriptResult {
  scriptPubKey: string;
}

export interface SelectCoinsInput {
  utxos: UTXOInput[];
  target: string;
  feePerByte: string;
  costOfChange: string;
}

export interface SelectCoinsResult {
  selected: SelectedUTXO[];
  total: string;
  effective: string;
  waste: string;
  exactMatch: boolean;
}

export interface SelectedUTXO {
  txid: string;
  vout: number;
  amount: string;
  fee: string;
  effectiveAmount: string;
  height: number;
}

export interface SignStreamResult {
  valueHex: string;
}

export interface StreamClaimResult {
  valueHex: string;
}

export interface TxInput {
  txid: string;
  vout: number;
  amount: string;
  scriptPubKey: string;
  chain: number;
  index: number;
}

export interface TxOutput {
  address: string;
  amount: string;
  isClaim: boolean;
  claimName: string;
  claimValueHex: string;
  claimIDHex: string;
  claimType: number;
}

export interface TxSizeResult {
  size: number;
}

export interface UTXOInput {
  txid: string;
  vout: number;
  amount: string;
  height: number;
}

export interface ValueHexResult {
  valueHex: string;
}

export interface WalletResult {
  handle: number;
  address: string;
}


// ── WASM Function Exports ──

/** claim namespace */
export interface WasmClaimExports {
  compileClaimValue(claimHex: string): WasmResult<{ valueHex: string }>;
  createChannelClaim(title: string, publicKeyHex: string): WasmResult<{ valueHex: string }>;
  createCollectionClaim(title: string, claimIDs: string[]): WasmResult<{ valueHex: string }>;
  createRepostClaim(title: string, claimID: string): WasmResult<{ valueHex: string }>;
  createStreamClaim(title: string, description: string, sdHash: string, mediaType: string, channelClaimID?: string): WasmResult<{ valueHex: string }>;
  parseClaimValue(claimHex: string): WasmResult<{ version: number; hasSignature: boolean; claimType: string; title: string; publicKeyHex?: string; mediaType?: string; sdHashHex?: string; claimIDHex?: string; signatureHex?: string }>;
  signStreamClaim(handle: number, valueHex: string, firstInputTxID: string, channelClaimIDHex: string, channelChain: number, channelIndex: number): WasmResult<{ valueHex: string }>;
}

/** coinselect namespace */
export interface WasmCoinselectExports {
  selectCoins(utxos: string, target: string, feePerByte: string, costOfChange?: string): WasmResult<{ selected: SelectedUTXO[]; total: string; effective: string; waste: string; exactMatch: boolean }>;
}

/** meta namespace */
export interface WasmMetaExports {
  ready: boolean;
}

/** tx namespace */
export interface WasmTxExports {
  buildTx(handle: number, inputs: string, outputs: string): WasmResult<{ txhex: string; txid: string }>;
  claimIDFromTxVout(txid: string, vout: number): WasmResult<{ claimIDHex: string }>;
  estimateFee(size: number, feePerByte: string): WasmResult<{ fee: string }>;
  estimateTxSize(inputCount: number, outputCount: number): WasmResult<{ size: number }>;
}

/** wallet namespace */
export interface WasmWalletExports {
  makeSeed(): WasmResult<{ mnemonic: string }>;
  walletAddress(handle: number): WasmResult<{ address: string }>;
  walletAddressAt(handle: number, chain: number, index: number): WasmResult<{ address: string }>;
  walletClose(handle: number): WasmResult<{ closed: boolean }>;
  walletFromMnemonic(mnemonic: string): WasmResult<{ handle: number; address: string }>;
  walletFromSeed(seed: string): WasmResult<{ handle: number; address: string }>;
  walletMnemonic(handle: number): WasmResult<{ mnemonic: string }>;
  walletPrivateKeyHex(handle: number): WasmResult<{ privateKey: string }>;
  walletPubKeyScriptAt(handle: number, chain: number, index: number): WasmResult<{ scriptPubKey: string }>;
  walletPublicKeyHex(handle: number): WasmResult<{ publicKey: string }>;
}

/** Full shape of the Go-WASM module exported to JS. */
export interface WasmExports {
  compileClaimValue: WasmClaimExports["compileClaimValue"];
  createChannelClaim: WasmClaimExports["createChannelClaim"];
  createCollectionClaim: WasmClaimExports["createCollectionClaim"];
  createRepostClaim: WasmClaimExports["createRepostClaim"];
  createStreamClaim: WasmClaimExports["createStreamClaim"];
  parseClaimValue: WasmClaimExports["parseClaimValue"];
  signStreamClaim: WasmClaimExports["signStreamClaim"];
  selectCoins: WasmCoinselectExports["selectCoins"];
  ready: boolean;
  buildTx: WasmTxExports["buildTx"];
  claimIDFromTxVout: WasmTxExports["claimIDFromTxVout"];
  estimateFee: WasmTxExports["estimateFee"];
  estimateTxSize: WasmTxExports["estimateTxSize"];
  makeSeed: WasmWalletExports["makeSeed"];
  walletAddress: WasmWalletExports["walletAddress"];
  walletAddressAt: WasmWalletExports["walletAddressAt"];
  walletClose: WasmWalletExports["walletClose"];
  walletFromMnemonic: WasmWalletExports["walletFromMnemonic"];
  walletFromSeed: WasmWalletExports["walletFromSeed"];
  walletMnemonic: WasmWalletExports["walletMnemonic"];
  walletPrivateKeyHex: WasmWalletExports["walletPrivateKeyHex"];
  walletPubKeyScriptAt: WasmWalletExports["walletPubKeyScriptAt"];
  walletPublicKeyHex: WasmWalletExports["walletPublicKeyHex"];
}
