name: Setup JS

description: Setup JS environment and dependencies

inputs:
  node_version:
    description: Node.js version
    required: false
    default: '20.10.0'

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}
        registry-url: https://registry.npmjs.org
    - uses: pnpm/action-setup@v3
      name: Install pnpm
      with:
        run_install: false
        version: 9.11.0
    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
    - name: Install dependencies
      run: pnpm install
      shell: bash
