/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Abuse Reporting API
 * API for submitting and tracking abuse reports
 * OpenAPI spec version: 1.0.0
 */
/**
 * Type of abuse being reported
 */
export type AbuseReportRequestAbuseType = typeof AbuseReportRequestAbuseType[keyof typeof AbuseReportRequestAbuseType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AbuseReportRequestAbuseType = {
  malicious_content: 'malicious_content',
  resource_abuse: 'resource_abuse',
  copyright_violation: 'copyright_violation',
  phishing_scam: 'phishing_scam',
  other: 'other',
} as const;

export interface AbuseReportRequest {
  /** Email address of the person reporting abuse */
  email: string;
  /** URL or content identifier where abuse was found */
  location: string;
  /** Type of abuse being reported */
  abuse_type?: AbuseReportRequestAbuseType;
  /**
   * Detailed description of the abuse
   * @minLength 10
   */
  description: string;
  /** Any additional information that may be relevant */
  additional_details?: string;
}

export interface AbuseReportResponse {
  /** Reference number for the report */
  confirmation_number: string;
  /** When the report was received */
  received_at: string;
  /** Optional informational message */
  message?: string;
}

/**
 * Current status of the report
 */
export type AbuseReportStatusResponseStatus = typeof AbuseReportStatusResponseStatus[keyof typeof AbuseReportStatusResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AbuseReportStatusResponseStatus = {
  received: 'received',
  under_review: 'under_review',
  action_taken: 'action_taken',
  closed: 'closed',
} as const;

export interface AbuseReportStatusResponse {
  /** Reference number for the report */
  confirmation_number: string;
  /** Current status of the report */
  status: AbuseReportStatusResponseStatus;
  /** When the report was submitted */
  submitted_at: string;
  /** When the report was last updated */
  last_updated_at?: string;
  /** Optional status message */
  message?: string;
}

export interface ProviderTemplateCreateRequest {
  /** Name of the provider template */
  name: string;
  /**
   * Processing priority (higher numbers processed first)
   * @minimum 1
   */
  priority?: number;
  /** List of domain patterns to match */
  domainPatterns?: string[];
  /** List of email header patterns to match */
  headerPatterns?: string[];
  /**
   * List of content patterns to match
   * @minItems 1
   */
  contentPatterns: string[];
}

export interface ProviderTemplateResponse {
  /** Whether the template was successfully registered */
  success: boolean;
  /** Informational message */
  message?: string;
}

/**
 * Additional error details
 */
export type ErrorResponseDetails = { [key: string]: unknown };

export interface ErrorResponse {
  /** Error message */
  error: string;
  /** Additional error details */
  details?: ErrorResponseDetails;
}

export interface TokenValidationRequest {
  /** Legacy access token to validate */
  token: string;
}

export interface TokenValidationResponse {
  /** Whether the token is valid */
  valid: boolean;
  /** Case reference number if valid */
  reference?: string;
}

export interface TokenRefreshRequest {
  /** Legacy access token to refresh */
  token: string;
}

export interface TokenRefreshResponse {
  /** New legacy access token */
  token: string;
  /** Number of days the token is valid */
  valid_days: number;
}

export interface TokenExchangeRequest {
  /** Legacy access token to exchange */
  token: string;
}

export interface TokenJWTCreateResponse {
  /** JWT token for API access */
  access_token: string;
  /** When the JWT token expires */
  expires_at: string;
}

