/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Abuse Reporting API
 * API for submitting and tracking abuse reports
 * OpenAPI spec version: 1.0.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  AbuseReportRequest,
  AbuseReportResponse,
  AbuseReportStatusResponse,
  TokenExchangeRequest,
  TokenJWTCreateResponse,
  TokenRefreshRequest,
  TokenRefreshResponse,
  TokenValidationRequest,
  TokenValidationResponse
} from './abuseReportingAPI.schemas';





  /**
 * Allows end users to submit reports about abusive content
 * @summary Submit an abuse report
 */
export const submitReport = <TData = AxiosResponse<AbuseReportResponse>>(
    abuseReportRequest: AbuseReportRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/abuse/report`,
      abuseReportRequest,options
    );
  }
/**
 * Check the status of a previously submitted abuse report
 * @summary Check report status
 */
export const getReportStatus = <TData = AxiosResponse<AbuseReportStatusResponse>>(
    confirmationNumber: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/abuse/report/${confirmationNumber}`,options
    );
  }
/**
 * Checks if a legacy access token is valid and returns case reference
 * @summary Validate an access token
 */
export const validateToken = <TData = AxiosResponse<TokenValidationResponse>>(
    tokenValidationRequest: TokenValidationRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/tokens/validate`,
      tokenValidationRequest,options
    );
  }
/**
 * Generates a new legacy access token with extended validity
 * @summary Refresh a legacy access token
 */
export const refreshToken = <TData = AxiosResponse<TokenRefreshResponse>>(
    tokenRefreshRequest: TokenRefreshRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/tokens/refresh`,
      tokenRefreshRequest,options
    );
  }
/**
 * Exchanges a legacy access token for a JWT token with 90-day validity
 * @summary Exchange legacy token for JWT
 */
export const exchangeToken = <TData = AxiosResponse<TokenJWTCreateResponse>>(
    tokenExchangeRequest: TokenExchangeRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/tokens/jwt`,
      tokenExchangeRequest,options
    );
  }
export type SubmitReportResult = AxiosResponse<AbuseReportResponse>
export type GetReportStatusResult = AxiosResponse<AbuseReportStatusResponse>
export type ValidateTokenResult = AxiosResponse<TokenValidationResponse>
export type RefreshTokenResult = AxiosResponse<TokenRefreshResponse>
export type ExchangeTokenResult = AxiosResponse<TokenJWTCreateResponse>
