import { fixImportsPlugin } from "esbuild-fix-imports-plugin";
import { defineConfig } from "tsup";

export default defineConfig([
  {
    bundle: false,
    clean: true,
    dts: true,
    entry: ["src/**/*"],
    esbuildPlugins: [fixImportsPlugin() as any],
    external: [],
    format: ["cjs"],
    outDir: "dist/cjs",
    outExtension: () => ({ js: ".cjs" }),
    sourcemap: true,
    target: "esnext",
    tsconfig: "./tsconfig.json",
  },
  {
    bundle: false,
    clean: true,
    dts: true,
    entry: ["src/**/*"],
    esbuildPlugins: [fixImportsPlugin() as any],
    external: [],
    format: ["esm"],
    outDir: "dist/esm",
    sourcemap: true,
    target: "esnext",
    tsconfig: "./tsconfig.json",
  },
  {
    bundle: false,
    clean: true,
    dts: false,
    entry: ["config/postcss.config.ts"],
    esbuildPlugins: [fixImportsPlugin() as any],
    format: ["cjs"],
    outDir: "dist/cjs/config",
    outExtension: () => ({ js: ".cjs" }),
    sourcemap: true,
    target: "esnext",
    tsconfig: "./tsconfig.json",
  },
  {
    bundle: false,
    clean: true,
    dts: true,
    entry: ["config/tailwind.config.ts"],
    esbuildPlugins: [fixImportsPlugin() as any],
    format: ["esm"],
    outDir: "dist/esm/config",
    sourcemap: true,
    target: "esnext",
    tsconfig: "./tsconfig.json",
  },
]);
