// All types are re-exported from portal-sdk — no local redefinitions
import type { PublicPricingPlanResponse as SDKPublicPricingPlanResponse } from "@lumeweb/portal-sdk";
export type {
  APIEndpointInfoResponse,
  BalanceResponse,
  ChangePlanRequest,
  CheckoutUIFragmentMetadata,
  CheckoutUIFragment,
  CheckoutUIResponseMetadata,
  CheckoutUIResponse,
  GatewayPublicInfo,
  GatewayListResponse,
  ManagementCapabilitiesResponseAdminOperations,
  ManagementCapabilitiesResponseOperations,
  ManagementCapabilitiesResponse,
  ManagementResultResponse,
  CheckoutSessionStatusResponse,
  SubscriptionStatusResponse,
  Uuid,
  UserCreditItem,
  UserCreditsListResponse,
  PublicPricingPlanPeriodDTO,
  PublicPricingPlansListResponse,
} from "@lumeweb/portal-sdk";

// Re-import for local use
import type {
  CheckoutUIFragment as ImportedCheckoutUIFragment,
  GatewayPublicInfo as ImportedGatewayPublicInfo,
  ManagementResultResponse as ImportedManagementResultResponse,
} from "@lumeweb/portal-sdk";

// Extended pricing plan type with features (from FeaturesJSON backend field)
// Note: SDK type has features as required, we override to make it compatible with backend response
export interface PublicPricingPlanResponse extends Omit<SDKPublicPricingPlanResponse, "features"> {
  features?: string[];
}

// --- Computed / helper types not generated by orval ---

export const MANAGEMENT_OPERATIONS = ["cancel", "change_plan", "customer_portal", "pause", "resume"] as const;
export type ManagementOperation = typeof MANAGEMENT_OPERATIONS[number];

export const MANAGEMENT_MODES = ["portal", "api"] as const;
export type ManagementMode = typeof MANAGEMENT_MODES[number];

export enum ManagementAction {
  Redirect = "redirect",
  ShowUI = "show_ui",
  ApiRequired = "api_required",
  CheckoutRequired = "checkout_required",
  Complete = "complete",
  Unsupported = "unsupported",
  Error = "error",
}

export type FragmentType =
  | "link"
  | "html"
  | "script"
  | "script_url"
  | "iframe"
  | "modal"
  | "button"
  | "form";

export enum SessionStatus {
  Open = "open",
  Complete = "complete",
  Expired = "expired",
}

// --- Type guards ---

export function isManagementOperation(value: string): value is ManagementOperation {
  return (MANAGEMENT_OPERATIONS as readonly string[]).includes(value);
}

export function isManagementAction(value: string): value is ManagementAction {
  return Object.values(ManagementAction).includes(value as ManagementAction);
}

export function isRedirectAction(
  action: ManagementAction,
): action is ManagementAction.Redirect {
  return action === ManagementAction.Redirect;
}

export function isShowUIAction(
  action: ManagementAction,
): action is ManagementAction.ShowUI {
  return action === ManagementAction.ShowUI;
}

export function isApiRequiredAction(
  action: ManagementAction,
): action is ManagementAction.ApiRequired {
  return action === ManagementAction.ApiRequired;
}

export function isUnsupportedAction(
  action: ManagementAction,
): action is ManagementAction.Unsupported {
  return action === ManagementAction.Unsupported;
}

export function isErrorAction(
  action: ManagementAction,
): action is ManagementAction.Error {
  return action === ManagementAction.Error;
}

export function isCheckoutRequiredAction(
  action: ManagementAction,
): action is ManagementAction.CheckoutRequired {
  return action === ManagementAction.CheckoutRequired;
}

// Extended from ManagementResultResponse for checkout_required action
// SDK's ManagementResultResponse doesn't include checkout-specific fields
export interface CheckoutRequiredResponse extends ImportedManagementResultResponse {
  action: "checkout_required";
  checkout_link?: string;
  credit_applied?: string;
  charge_due?: string;
  effective_date?: string;
  fragments?: ImportedCheckoutUIFragment[];
}

// Plan change checkout data (when checkout_required is returned from change-plan API)
export interface PlanChangeCheckoutData {
  fragments: ImportedCheckoutUIFragment[];
  sessionId: string;
  gateway: ImportedGatewayPublicInfo;
}

export function isCheckoutRequiredResponse(
  response: unknown,
): response is CheckoutRequiredResponse {
  return (
    typeof response === "object" &&
    response !== null &&
    "action" in response &&
    response.action === "checkout_required"
  );
}

export interface CompleteResponse extends ImportedManagementResultResponse {
  action: "complete";
  credit_applied?: string;
  charge_due?: string;
  effective_date?: string;
}

export function isCompleteResponse(
  response: unknown,
): response is CompleteResponse {
  return (
    typeof response === "object" &&
    response !== null &&
    "action" in response &&
    response.action === "complete"
  );
}

const FRAGMENT_TYPES: readonly FragmentType[] = [
  "link",
  "html",
  "script",
  "script_url",
  "iframe",
  "modal",
  "button",
  "form",
] as const;

export function isFragmentType(value: string): value is FragmentType {
  return (FRAGMENT_TYPES as readonly string[]).includes(value);
}

export function assertNever(x: never): never {
  throw new Error(`Unhandled discriminated union member: ${x}`);
}

// SSE Event Types — must match backend SSEEventType constants in portal-plugin-billing
export enum BillingSSEEventType {
  PaymentCompleted = "payment.completed",
  SubscriptionActive = "subscription.active",
  SubscriptionCreated = "subscription.created",
  SubscriptionUpdated = "subscription.updated",
  SubscriptionCancelled = "subscription.cancelled",
  PlanChanged = "plan.changed",
  PlanChangedCreditOnly = "plan.changed.credit_only",
  PlanChangedZeroAmount = "plan.changed.zero_amount",
}

// -- SSE Event Data Types (match backend event structs, server-only fields omitted) --

export interface PaymentCompletedEventData {
  amount: string;
  gateway: string;
  invoice_id: string;
  external_id: string;
  paid_at: string;
}

export interface SubscriptionCreatedEventData {
  subscription_id: string;
  gateway: string;
  plan_id: number;
  period_id: number;
  created_at: string;
}

export interface SubscriptionActiveEventData {
  subscription_id: string;
  gateway: string;
  plan_id: number;
  period_id: number;
  activated_at: string;
}

export interface SubscriptionUpdatedEventData {
  subscription_id: string;
  gateway: string;
  old_plan_id?: number;
  new_plan_id: number;
  old_period_id?: number;
  new_period_id: number;
  updated_at: string;
}

export interface SubscriptionCancelledEventData {
  subscription_id: string;
  gateway: string;
  plan_id: number;
  cancelled_at: string;
}

export interface PlanChangedEventData {
  subscription_id: string;
  gateway: string;
  old_plan_id: number;
  old_period_id: number;
  new_plan_id: number;
  new_period_id: number;
  prorated_credit: string;
  prorated_charge: string;
  net_amount: string;
  changed_at: string;
}

export interface PlanChangeCreditOnlyEventData {
  subscription_id: string;
  gateway: string;
  old_plan_id: number;
  old_period_id: number;
  new_plan_id: number;
  new_period_id: number;
  credit_amount: string;
  effective_from: string;
  billing_cycle_end: string;
  completed_at: string;
}

export interface PlanChangeZeroAmountEventData {
  subscription_id: string;
  gateway: string;
  old_plan_id: number;
  old_period_id: number;
  new_plan_id: number;
  new_period_id: number;
  prorated_credit: string;
  prorated_charge: string;
  effective_from: string;
  billing_cycle_end: string;
  completed_at: string;
}

export type BillingSSEEventDataMap = {
  [BillingSSEEventType.PaymentCompleted]: PaymentCompletedEventData;
  [BillingSSEEventType.SubscriptionActive]: SubscriptionActiveEventData;
  [BillingSSEEventType.SubscriptionCreated]: SubscriptionCreatedEventData;
  [BillingSSEEventType.SubscriptionUpdated]: SubscriptionUpdatedEventData;
  [BillingSSEEventType.SubscriptionCancelled]: SubscriptionCancelledEventData;
  [BillingSSEEventType.PlanChanged]: PlanChangedEventData;
  [BillingSSEEventType.PlanChangedCreditOnly]: PlanChangeCreditOnlyEventData;
  [BillingSSEEventType.PlanChangedZeroAmount]: PlanChangeZeroAmountEventData;
};

export interface BillingSSEEvent<T extends BillingSSEEventType = BillingSSEEventType> {
  event: T;
  data: BillingSSEEventDataMap[T];
  id?: string;
  retry?: number;
}
