import type { Metadata } from "next"
import Image  from "next/image"
import { Inter, Jaldi } from "next/font/google"
import "./globals.css"
import Header from "@/components/LayoutHeader"
import Footer from "@/components/LayoutFooter"

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" })
const jaldi = Jaldi({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-jaldi"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`font-main bg-gray-900 flex`}>
        <main className="flex w-full min-h-screen flex-col md:px-40 items-center py-16 mx-auto">
          <Header />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  )
}
