import type { Metadata } from "next"
import { Jaldi, Be_Vietnam_Pro } from "next/font/google"
import Header from "@/components/LayoutHeader"
import Footer from "@/components/LayoutFooter"
import "./globals.css"

const beVietnamPro = Be_Vietnam_Pro({ weight: ["400"], subsets: ["latin"], variable: "--font-be-vietnam-pro" })
const jaldi = Jaldi({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-jaldi"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`font-main bg-gray-900 flex ${beVietnamPro.variable} ${jaldi.variable}`}>
        <main className="dark flex w-full min-h-screen flex-col md:px-40 items-center py-16 mx-auto">
          <Header />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  )
}
