/**
 * Generated OpenAPI HTTP client functions.
 *
 * This module exports the raw generated HTTP functions from the OpenAPI specification.
 * Use these if you need direct access to the generated API endpoints without the
 * higher-level AccountApi abstraction.
 *
 * Note: These are auto-generated by Orval and should not be edited manually.
 */

export * from "@/account/generated";
export * from "@/account/generated/accountAPI.schemas";
