/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * LBRY Stream API
 * LBRY Stream API for uploading and managing streams on the LBRY network. Supports stream uploads with metadata management and LBRY network operations.
 * OpenAPI spec version: develop
 */
export interface CreateDeviceRequest {
  ip_address: string;
  name: string;
}

export interface DeviceResponse {
  created_at: string;
  id: number;
  ip_address: string;
  name: string;
  updated_at: string;
  user_id: number;
}

export interface DeviceResponseResponse {
  data: DeviceResponse;
  total: number;
}

export interface ErrorResponse {
  error: string;
}

export interface PostStreamUploadResponse {
  upload_hash: string;
}

export interface StreamPinRequest {
  sd_hash: string;
}

export interface StreamResponse {
  created_at: string;
  id: number;
  sd_hash: string;
  size: number;
  stream_hash: string;
  stream_name: string;
  stream_type: string;
  suggested_file_name: string;
  updated_at: string;
}

export interface StreamResponseResponse {
  data: StreamResponse;
  total: number;
}

export interface UpdateDeviceRequest {
  name: string;
}

export type PostApiStreamsUploadBody = {
  file: Blob;
};

export type PostApiStreamsUploadTusBody = { [key: string]: unknown };

export type PatchApiStreamsUploadTusIdBody = { [key: string]: unknown };

