name: Build

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout all commits
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup
        uses: LumeWeb/workflows/.github/actions/setup-all@develop
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
      - name: Setup TinyGo
        uses: acifani/setup-tinygo@v2
        with:
          tinygo-version: "0.36.0"
      - name: Set TinyGo env
        run: |
          echo "TINYGOROOT=$(dirname $(dirname $(which tinygo)))" >> "$GITHUB_ENV"
          echo "TINYGOPATH=$(which tinygo)" >> "$GITHUB_ENV"
          echo "$(dirname $(which tinygo))" >> "$GITHUB_PATH"
      - name: Generate contract types
        run: pnpm --filter=@lumeweb/lbry-sdk generate
      - name: Install pinner-cli
        uses: ./.github/actions/setup-pinner-cli
      - name: Build
        run: pnpm build
