name: Deploy lumeweb.com

on:
  push:
    branches:
      - develop
    paths:
      - "apps/lumeweb.com/**"
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}
permissions:
  deployments: write
  contents: read

jobs:
  deploy:
    name: Deploy lumeweb.com
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
      - name: Setup
        uses: LumeWeb/workflows/.github/actions/setup-all@develop
      - name: Build
        run: pnpm build:lumeweb.com
      - name: Write IndexNow key file
        uses: ./.github/actions/indexnow-write-key
        with:
          public-path: apps/lumeweb.com/dist
          key: ${{ vars.INDEXNOW_KEY_LUMEWEB }}
      - name: Deploy to IPFS via Pinner
        id: deploy_pinner
        uses: lumeweb/pinner-deploy-action@v0
        with:
          api-key: ${{ secrets.PINNER_API_KEY }}
          path: apps/lumeweb.com/dist
          domain: lumeweb.com
          remove-previous: true
      - name: Submit URLs to IndexNow
        uses: ./.github/actions/indexnow
        with:
          build-path: apps/lumeweb.com/dist
          site: lumeweb.com
          key: ${{ vars.INDEXNOW_KEY_LUMEWEB }}
