name: Deploy docs.lumeweb.com

on:
  push:
    branches:
      - '**'
    paths:
      - 'apps/docs.lumeweb.com/**'
  pull_request:
    branches:
      - '**'
    paths:
      - 'apps/docs.lumeweb.com/**'
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}
permissions:
  pull-requests: write
  deployments: write
  contents: read


jobs:
  build:
    name: Deploy docs.lumeweb.com
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup-all
        with:
          node_version: 20.10.0
          go_version: 1.23.0
      - name: Build
        run: pnpm build:docs.lumeweb.com
      - name: Publish to Cloudflare Pages
        id: deploy_cf
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: docs-lumeweb-com
          directory: dist/apps/docs.lumeweb.com
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
      - uses: mshick/add-pr-comment@v2
        if: github.event_name == 'pull_request'
        with:
          message: |
            The docs.lumeweb.com has been deployed to [Staging](${{ steps.deploy_cf.outputs.url }}).
