name: Release Go modules

concurrency: commits-to-master

on:
  repository_dispatch:
    types: [release-go]
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get_modified_apps.outputs.matrix }}
      changes_exist: ${{ steps.release.outputs.changes_exist }}
      commit_hash: ${{ steps.release.outputs.commit_hash }}
    steps:
      - name: Checkout all commits
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup-all
        with:
          node_version: 20.10.0
          go_version: 1.23.0

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Release
        id: release
        run: |
          ./scripts/release-go.sh
          if [ -n "$(git status --porcelain)" ]; then
            git push origin HEAD:develop
            echo "changes_exist=true" >> "$GITHUB_OUTPUT"
            echo "commit_hash=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"
          else
            echo "changes_exist=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Get modified apps info
        if: steps.release.outputs.changes_exist == 'true'
        id: get_modified_apps
        run: |
          # Create matrix parameter directly from the files
          matrix=$(paste -d, /tmp/modified_apps.txt /tmp/module_versions.txt | \
            jq -R 'split(",") | {app: .[0], version: .[1]}' | \
            jq -s '{include: .}' | tr -d '\n')
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"

  dispatch:
    needs: prepare
    if: needs.prepare.outputs.changes_exist == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.prepare.outputs.matrix) }}
    steps:
      - name: Dispatch UI update
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT_REPOSITORY_DISPATCH }}
          repository: LumeWeb/portal-plugin-${{ matrix.app }}
          event-type: update-ui
          client-payload: |
            {
              "commit_hash": "${{ needs.prepare.outputs.commit_hash }}",
              "version": "${{ matrix.version }}",
              "app_name": "${{ matrix.app }}",
              "repository": "${{ github.repository }}",
              "ref": "${{ github.ref }}"
            }
