name: Release Go modules

concurrency: commits-to-master

on:
  repository_dispatch:
    types: [release-go]
  workflow_dispatch:

jobs:
  release-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout all commits
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup-all
        with:
          node_version: 20.10.0
          go_version: 1.23.0

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Release
        run: |
          ./scripts/release-go.sh
          if [ -n "$(git status --porcelain)" ]; then
            echo "CHANGES_EXIST=true" >> $GITHUB_ENV
          else
            echo "CHANGES_EXIST=false" >> $GITHUB_ENV
          fi

      - name: Push changes and tags
        if: env.CHANGES_EXIST == 'true'
        run: |
          git push origin HEAD:develop
          git push --tags

      - name: Cleanup
        run: |
          git checkout develop
          git branch -D release || true
